const dist = [
    {dist_code:"8103",dist_th:"เกาะลันตา",dist_en:"Ko Lanta"},
{dist_code:"8102",dist_th:"เขาพนม",dist_en:"Khao Phanom"},
{dist_code:"8104",dist_th:"คลองท่อม",dist_en:"Khlong Thom"},
{dist_code:"8106",dist_th:"ปลายพระยา",dist_en:"Plai Phraya"},
{dist_code:"8101",dist_th:"เมืองกระบี่",dist_en:"Mueang Krabi"},
{dist_code:"8107",dist_th:"ลำทับ",dist_en:"Lam Thap"},
{dist_code:"8108",dist_th:"เหนือคลอง",dist_en:"Nuea Khlong"},
{dist_code:"8105",dist_th:"อ่าวลึก",dist_en:"Ao Luek"},
{dist_code:"1033",dist_th:"คลองเตย",dist_en:"Khlong Toei"},
{dist_code:"1018",dist_th:"คลองสาน",dist_en:"Khlong San"},
{dist_code:"1046",dist_th:"คลองสามวา",dist_en:"Khlong Sam Wa"},
{dist_code:"1043",dist_th:"คันนายาว",dist_en:"Khan Na Yao"},
{dist_code:"1030",dist_th:"จตุจักร",dist_en:"Chatuchak"},
{dist_code:"1035",dist_th:"จอมทอง",dist_en:"Chom Thong"},
{dist_code:"1036",dist_th:"ดอนเมือง",dist_en:"Don Mueang"},
{dist_code:"1026",dist_th:"ดินแดง",dist_en:"Din Daeng"},
{dist_code:"1002",dist_th:"ดุสิต",dist_en:"Dusit"},
{dist_code:"1019",dist_th:"ตลิ่งชัน",dist_en:"Taling Chan"},
{dist_code:"1048",dist_th:"ทวีวัฒนา",dist_en:"Thawi Watthana"},
{dist_code:"1049",dist_th:"ทุ่งครุ",dist_en:"Thung Khru"},
{dist_code:"1015",dist_th:"ธนบุรี",dist_en:"Thon Buri"},
{dist_code:"1020",dist_th:"บางกอกน้อย",dist_en:"Bangkok Noi"},
{dist_code:"1016",dist_th:"บางกอกใหญ่",dist_en:"Bangkok Yai"},
{dist_code:"1006",dist_th:"บางกะปิ",dist_en:"Bang Kapi"},
{dist_code:"1021",dist_th:"บางขุนเทียน",dist_en:"Bang Khun Thian"},
{dist_code:"1005",dist_th:"บางเขน",dist_en:"Bang Khen"},
{dist_code:"1031",dist_th:"บางคอแหลม",dist_en:"Bang Kho Laem"},
{dist_code:"1040",dist_th:"บางแค",dist_en:"Bang Khae"},
{dist_code:"1029",dist_th:"บางซื่อ",dist_en:"Bang Sue"},
{dist_code:"1047",dist_th:"บางนา",dist_en:"Bang Na"},
{dist_code:"1050",dist_th:"บางบอน",dist_en:"Bang Bon"},
{dist_code:"1025",dist_th:"บางพลัด",dist_en:"Bang Phlat"},
{dist_code:"1004",dist_th:"บางรัก",dist_en:"Bang Rak"},
{dist_code:"1027",dist_th:"บึงกุ่ม",dist_en:"Bueng Kum"},
{dist_code:"1007",dist_th:"ปทุมวัน",dist_en:"Pathum Wan"},
{dist_code:"1032",dist_th:"ประเวศ",dist_en:"Prawet"},
{dist_code:"1008",dist_th:"ป้อมปราบศัตรูพ่าย",dist_en:"Pom Prap Sattru Phai"},
{dist_code:"1014",dist_th:"พญาไท",dist_en:"Phaya Thai"},
{dist_code:"1009",dist_th:"พระโขนง",dist_en:"Phra Khanong"},
{dist_code:"1001",dist_th:"พระนคร",dist_en:"Phra Nakhon"},
{dist_code:"1022",dist_th:"ภาษีเจริญ",dist_en:"Phasi Charoen"},
{dist_code:"1010",dist_th:"มีนบุรี",dist_en:"Min Buri"},
{dist_code:"1012",dist_th:"ยานนาวา",dist_en:"Yan Nawa"},
{dist_code:"1037",dist_th:"ราชเทวี",dist_en:"Ratchathewi"},
{dist_code:"1024",dist_th:"ราษฎร์บูรณะ",dist_en:"Rat Burana"},
{dist_code:"1011",dist_th:"ลาดกระบัง",dist_en:"Lat Krabang"},
{dist_code:"1038",dist_th:"ลาดพร้าว",dist_en:"Lat Phrao"},
{dist_code:"1045",dist_th:"วังทองหลาง",dist_en:"Wang Thonglang"},
{dist_code:"1039",dist_th:"วัฒนา",dist_en:"Vadhana"},
{dist_code:"1034",dist_th:"สวนหลวง",dist_en:"Suan Luang"},
{dist_code:"1044",dist_th:"สะพานสูง",dist_en:"Saphan Sung"},
{dist_code:"1013",dist_th:"สัมพันธวงศ์",dist_en:"Samphanthawong"},
{dist_code:"1028",dist_th:"สาทร",dist_en:"Sathon"},
{dist_code:"1042",dist_th:"สายไหม",dist_en:"Sai Mai"},
{dist_code:"1023",dist_th:"หนองแขม",dist_en:"Nong Khaem"},
{dist_code:"1003",dist_th:"หนองจอก",dist_en:"Nong Chok"},
{dist_code:"1041",dist_th:"หลักสี่",dist_en:"Lak Si"},
{dist_code:"1017",dist_th:"ห้วยขวาง",dist_en:"Huai Khwang"},
{dist_code:"7111",dist_th:"ด่านมะขามเตี้ย",dist_en:"Dan Makham Tia"},
{dist_code:"7107",dist_th:"ทองผาภูมิ",dist_en:"Thong Pha Phum"},
{dist_code:"7106",dist_th:"ท่าม่วง",dist_en:"Tha Muang"},
{dist_code:"7105",dist_th:"ท่ามะกา",dist_en:"Tha Maka"},
{dist_code:"7102",dist_th:"ไทรโยค",dist_en:"Sai Yok"},
{dist_code:"7103",dist_th:"บ่อพลอย",dist_en:"Bo Phloi"},
{dist_code:"7109",dist_th:"พนมทวน",dist_en:"Phanom Thuan"},
{dist_code:"7101",dist_th:"เมืองกาญจนบุรี",dist_en:"Mueang Kanchanaburi"},
{dist_code:"7110",dist_th:"เลาขวัญ",dist_en:"Lao Khwan"},
{dist_code:"7104",dist_th:"ศรีสวัสดิ์",dist_en:"Si Sawat"},
{dist_code:"7108",dist_th:"สังขละบุรี",dist_en:"Sangkhla Buri"},
{dist_code:"7112",dist_th:"หนองปรือ",dist_en:"Nong Prue"},
{dist_code:"7113",dist_th:"ห้วยกระเจา",dist_en:"Huai Krachao"},
{dist_code:"4603",dist_th:"กมลาไสย",dist_en:"Kamalasai"},
{dist_code:"4605",dist_th:"กุฉินารายณ์",dist_en:"Kuchinarai"},
{dist_code:"4606",dist_th:"เขาวง",dist_en:"Khao Wong"},
{dist_code:"4610",dist_th:"คำม่วง",dist_en:"Kham Muang"},
{dist_code:"4618",dist_th:"ฆ้องชัย",dist_en:"Khong Chai"},
{dist_code:"4617",dist_th:"ดอนจาน",dist_en:"Don Chan"},
{dist_code:"4611",dist_th:"ท่าคันโท",dist_en:"Tha Khantho"},
{dist_code:"4616",dist_th:"นาคู",dist_en:"Na Khu"},
{dist_code:"4602",dist_th:"นามน",dist_en:"Na Mon"},
{dist_code:"4601",dist_th:"เมืองกาฬสินธุ์",dist_en:"Mueang Kalasin"},
{dist_code:"4607",dist_th:"ยางตลาด",dist_en:"Yang Talat"},
{dist_code:"4604",dist_th:"ร่องคำ",dist_en:"Rong Kham"},
{dist_code:"4613",dist_th:"สมเด็จ",dist_en:"Somdet"},
{dist_code:"4609",dist_th:"สหัสขันธ์",dist_en:"Sahatsakhan"},
{dist_code:"4615",dist_th:"สามชัย",dist_en:"Sam Chai"},
{dist_code:"4612",dist_th:"หนองกุงศรี",dist_en:"Nong Kung Si"},
{dist_code:"4614",dist_th:"ห้วยผึ้ง",dist_en:"Huai Phueng"},
{dist_code:"4608",dist_th:"ห้วยเม็ก",dist_en:"Huai Mek"},
{dist_code:"6211",dist_th:"โกสัมพีนคร",dist_en:"Kosamphi Nakhon"},
{dist_code:"6204",dist_th:"ขาณุวรลักษบุรี",dist_en:"Khanu Woralaksaburi"},
{dist_code:"6205",dist_th:"คลองขลุง",dist_en:"Khlong Khlung"},
{dist_code:"6203",dist_th:"คลองลาน",dist_en:"Khlong Lan"},
{dist_code:"6208",dist_th:"ทรายทองวัฒนา",dist_en:"Sai Thong Watthana"},
{dist_code:"6202",dist_th:"ไทรงาม",dist_en:"Sai Ngam"},
{dist_code:"6210",dist_th:"บึงสามัคคี",dist_en:"Bueng Samakkhi"},
{dist_code:"6209",dist_th:"ปางศิลาทอง",dist_en:"Pang Sila Thong"},
{dist_code:"6206",dist_th:"พรานกระต่าย",dist_en:"Phran Kratai"},
{dist_code:"6201",dist_th:"เมืองกำแพงเพชร",dist_en:"Mueang Kamphaeng Phet"},
{dist_code:"6207",dist_th:"ลานกระบือ",dist_en:"Lan Krabue"},
{dist_code:"4009",dist_th:"กระนวน",dist_en:"Kranuan"},
{dist_code:"4019",dist_th:"เขาสวนกวาง",dist_en:"Khao Suan Kwang"},
{dist_code:"4022",dist_th:"โคกโพธิ์ไชย",dist_en:"Khok Pho Chai"},
{dist_code:"4018",dist_th:"ชนบท",dist_en:"Chonnabot"},
{dist_code:"4005",dist_th:"ชุมแพ",dist_en:"Chum Phae"},
{dist_code:"4021",dist_th:"ซำสูง",dist_en:"Sam Sung"},
{dist_code:"4007",dist_th:"น้ำพอง",dist_en:"Nam Phong"},
{dist_code:"4025",dist_th:"โนนศิลา",dist_en:"Non Sila"},
{dist_code:"4010",dist_th:"บ้านไผ่",dist_en:"Ban Phai"},
{dist_code:"4002",dist_th:"บ้านฝาง",dist_en:"Ban Fang"},
{dist_code:"4024",dist_th:"บ้านแฮด",dist_en:"Ban Haet"},
{dist_code:"4011",dist_th:"เปือยน้อย",dist_en:"Pueai Noi"},
{dist_code:"4003",dist_th:"พระยืน",dist_en:"Phra Yuen"},
{dist_code:"4012",dist_th:"พล",dist_en:"Phon"},
{dist_code:"4020",dist_th:"ภูผาม่าน",dist_en:"Phu Pha Man"},
{dist_code:"4016",dist_th:"ภูเวียง",dist_en:"Phu Wiang"},
{dist_code:"4017",dist_th:"มัญจาคีรี",dist_en:"Mancha Khiri"},
{dist_code:"4001",dist_th:"เมืองขอนแก่น",dist_en:"Mueang Khon Kaen"},
{dist_code:"4029",dist_th:"เวียงเก่า",dist_en:"Wiang Kao"},
{dist_code:"4014",dist_th:"แวงน้อย",dist_en:"Waeng Noi"},
{dist_code:"4013",dist_th:"แวงใหญ่",dist_en:"Waeng Yai"},
{dist_code:"4006",dist_th:"สีชมพู",dist_en:"Si Chomphu"},
{dist_code:"4023",dist_th:"หนองนาคำ",dist_en:"Nong Na Kham"},
{dist_code:"4004",dist_th:"หนองเรือ",dist_en:"Nong Ruea"},
{dist_code:"4015",dist_th:"หนองสองห้อง",dist_en:"Nong Song Hong"},
{dist_code:"4008",dist_th:"อุบลรัตน์",dist_en:"Ubolratana"},
{dist_code:"2208",dist_th:"แก่งหางแมว",dist_en:"Kaeng Hang Maeo"},
{dist_code:"2202",dist_th:"ขลุง",dist_en:"Khlung"},
{dist_code:"2210",dist_th:"เขาคิชฌกูฏ",dist_en:"Khao Khitchakut"},
{dist_code:"2203",dist_th:"ท่าใหม่",dist_en:"Tha Mai"},
{dist_code:"2209",dist_th:"นายายอาม",dist_en:"Na Yai Am"},
{dist_code:"2204",dist_th:"โป่งน้ำร้อน",dist_en:"Pong Nam Ron"},
{dist_code:"2205",dist_th:"มะขาม",dist_en:"Makham"},
{dist_code:"2201",dist_th:"เมืองจันทบุรี",dist_en:"Mueang Chanthaburi"},
{dist_code:"2207",dist_th:"สอยดาว",dist_en:"Soi Dao"},
{dist_code:"2206",dist_th:"แหลมสิงห์",dist_en:"Laem Sing"},
{dist_code:"2411",dist_th:"คลองเขื่อน",dist_en:"Khlong Khuean"},
{dist_code:"2410",dist_th:"ท่าตะเกียบ",dist_en:"Tha Takiap"},
{dist_code:"2402",dist_th:"บางคล้า",dist_en:"Bang Khla"},
{dist_code:"2403",dist_th:"บางน้ำเปรี้ยว",dist_en:"Bang Nam Priao"},
{dist_code:"2404",dist_th:"บางปะกง",dist_en:"Bang Pakong"},
{dist_code:"2405",dist_th:"บ้านโพธิ์",dist_en:"Ban Pho"},
{dist_code:"2409",dist_th:"แปลงยาว",dist_en:"Plaeng Yao"},
{dist_code:"2406",dist_th:"พนมสารคาม",dist_en:"Phanom Sarakham"},
{dist_code:"2401",dist_th:"เมืองฉะเชิงเทรา",dist_en:"Mueang Chachoengsao"},
{dist_code:"2407",dist_th:"ราชสาส์น",dist_en:"Ratchasan"},
{dist_code:"2408",dist_th:"สนามชัยเขต",dist_en:"Sanam Chai Khet"},
{dist_code:"2011",dist_th:"เกาะจันทร์",dist_en:"Ko Chan"},
{dist_code:"2008",dist_th:"เกาะสีชัง",dist_en:"Ko Si Chang"},
{dist_code:"2010",dist_th:"บ่อทอง",dist_en:"Bo Thong"},
{dist_code:"2004",dist_th:"บางละมุง",dist_en:"Bang Lamung"},
{dist_code:"2002",dist_th:"บ้านบึง",dist_en:"Ban Bueng"},
{dist_code:"2006",dist_th:"พนัสนิคม",dist_en:"Phanat Nikhom"},
{dist_code:"2005",dist_th:"พานทอง",dist_en:"Phan Thong"},
{dist_code:"2001",dist_th:"เมืองชลบุรี",dist_en:"Mueang Chon Buri"},
{dist_code:"2007",dist_th:"ศรีราชา",dist_en:"Si Racha"},
{dist_code:"2009",dist_th:"สัตหีบ",dist_en:"Sattahip"},
{dist_code:"2003",dist_th:"หนองใหญ่",dist_en:"Nong Yai"},
{dist_code:"1808",dist_th:"เนินขาม",dist_en:"Noen Kham"},
{dist_code:"1802",dist_th:"มโนรมย์",dist_en:"Manorom"},
{dist_code:"1801",dist_th:"เมืองชัยนาท",dist_en:"Mueang Chai Nat"},
{dist_code:"1803",dist_th:"วัดสิงห์",dist_en:"Wat Sing"},
{dist_code:"1805",dist_th:"สรรคบุรี",dist_en:"Sankhaburi"},
{dist_code:"1804",dist_th:"สรรพยา",dist_en:"Sapphaya"},
{dist_code:"1807",dist_th:"หนองมะโมง",dist_en:"Nong Mamong"},
{dist_code:"1806",dist_th:"หันคา",dist_en:"Hankha"},
{dist_code:"3604",dist_th:"เกษตรสมบูรณ์",dist_en:"Kaset Sombun"},
{dist_code:"3612",dist_th:"แก้งคร้อ",dist_en:"Kaeng Khro"},
{dist_code:"3603",dist_th:"คอนสวรรค์",dist_en:"Khon Sawan"},
{dist_code:"3613",dist_th:"คอนสาร",dist_en:"Khon San"},
{dist_code:"3606",dist_th:"จัตุรัส",dist_en:"Chatturat"},
{dist_code:"3616",dist_th:"ซับใหญ่",dist_en:"Sap Yai"},
{dist_code:"3609",dist_th:"เทพสถิต",dist_en:"Thep Sathit"},
{dist_code:"3615",dist_th:"เนินสง่า",dist_en:"Noen Sa-Nga"},
{dist_code:"3602",dist_th:"บ้านเขว้า",dist_en:"Ban Khwao"},
{dist_code:"3611",dist_th:"บ้านแท่น",dist_en:"Ban Thaen"},
{dist_code:"3607",dist_th:"บำเหน็จณรงค์",dist_en:"Bamnet Narong"},
{dist_code:"3614",dist_th:"ภักดีชุมพล",dist_en:"Phakdi Chumphon"},
{dist_code:"3610",dist_th:"ภูเขียว",dist_en:"Phu Khiao"},
{dist_code:"3601",dist_th:"เมืองชัยภูมิ",dist_en:"Mueang Chaiyaphum"},
{dist_code:"3605",dist_th:"หนองบัวแดง",dist_en:"Nong Bua Daeng"},
{dist_code:"3608",dist_th:"หนองบัวระเหว",dist_en:"Nong Bua Rawe"},
{dist_code:"8602",dist_th:"ท่าแซะ",dist_en:"Tha Sae"},
{dist_code:"8608",dist_th:"ทุ่งตะโก",dist_en:"Thung Tako"},
{dist_code:"8603",dist_th:"ปะทิว",dist_en:"Pathio"},
{dist_code:"8606",dist_th:"พะโต๊ะ",dist_en:"Phato"},
{dist_code:"8601",dist_th:"เมืองชุมพร",dist_en:"Mueang Chumphon"},
{dist_code:"8605",dist_th:"ละแม",dist_en:"Lamae"},
{dist_code:"8607",dist_th:"สวี",dist_en:"Sawi"},
{dist_code:"8604",dist_th:"หลังสวน",dist_en:"Lang Suan"},
{dist_code:"5714",dist_th:"ขุนตาล",dist_en:"Khun Tan"},
{dist_code:"5703",dist_th:"เชียงของ",dist_en:"Chiang Khong"},
{dist_code:"5708",dist_th:"เชียงแสน",dist_en:"Chiang Saen"},
{dist_code:"5718",dist_th:"ดอยหลวง",dist_en:"Doi Luang"},
{dist_code:"5704",dist_th:"เทิง",dist_en:"Thoeng"},
{dist_code:"5706",dist_th:"ป่าแดด",dist_en:"Pa Daet"},
{dist_code:"5712",dist_th:"พญาเม็งราย",dist_en:"Phaya Mengrai"},
{dist_code:"5705",dist_th:"พาน",dist_en:"Phan"},
{dist_code:"5701",dist_th:"เมืองเชียงราย",dist_en:"Mueang Chiang Rai"},
{dist_code:"5707",dist_th:"แม่จัน",dist_en:"Mae Chan"},
{dist_code:"5715",dist_th:"แม่ฟ้าหลวง",dist_en:"Mae Fa Luang"},
{dist_code:"5716",dist_th:"แม่ลาว",dist_en:"Mae Lao"},
{dist_code:"5710",dist_th:"แม่สรวย",dist_en:"Mae Suai"},
{dist_code:"5709",dist_th:"แม่สาย",dist_en:"Mae Sai"},
{dist_code:"5713",dist_th:"เวียงแก่น",dist_en:"Wiang Kaen"},
{dist_code:"5702",dist_th:"เวียงชัย",dist_en:"Wiang Chai"},
{dist_code:"5717",dist_th:"เวียงเชียงรุ้ง",dist_en:"Wiang Chiang Rung"},
{dist_code:"5711",dist_th:"เวียงป่าเป้า",dist_en:"Wiang Pa Pao"},
{dist_code:"5025",dist_th:"กัลยาณิวัฒนา",dist_en:"Galyani Vadhana"},
{dist_code:"5002",dist_th:"จอมทอง",dist_en:"Chom Thong"},
{dist_code:"5004",dist_th:"เชียงดาว",dist_en:"Chiang Dao"},
{dist_code:"5021",dist_th:"ไชยปราการ",dist_en:"Chai Prakan"},
{dist_code:"5017",dist_th:"ดอยเต่า",dist_en:"Doi Tao"},
{dist_code:"5005",dist_th:"ดอยสะเก็ด",dist_en:"Doi Saket"},
{dist_code:"5024",dist_th:"ดอยหล่อ",dist_en:"Doi Lo"},
{dist_code:"5009",dist_th:"ฝาง",dist_en:"Fang"},
{dist_code:"5011",dist_th:"พร้าว",dist_en:"Phrao"},
{dist_code:"5001",dist_th:"เมืองเชียงใหม่",dist_en:"Mueang Chiang Mai"},
{dist_code:"5003",dist_th:"แม่แจ่ม",dist_en:"Mae Chaem"},
{dist_code:"5006",dist_th:"แม่แตง",dist_en:"Mae Taeng"},
{dist_code:"5007",dist_th:"แม่ริม",dist_en:"Mae Rim"},
{dist_code:"5022",dist_th:"แม่วาง",dist_en:"Mae Wang"},
{dist_code:"5023",dist_th:"แม่ออน",dist_en:"Mae On"},
{dist_code:"5010",dist_th:"แม่อาย",dist_en:"Mae Ai"},
{dist_code:"5020",dist_th:"เวียงแหง",dist_en:"Wiang Haeng"},
{dist_code:"5008",dist_th:"สะเมิง",dist_en:"Samoeng"},
{dist_code:"5013",dist_th:"สันกำแพง",dist_en:"San Kamphaeng"},
{dist_code:"5014",dist_th:"สันทราย",dist_en:"San Sai"},
{dist_code:"5012",dist_th:"สันป่าตอง",dist_en:"San Pa Tong"},
{dist_code:"5019",dist_th:"สารภี",dist_en:"Saraphi"},
{dist_code:"5015",dist_th:"หางดง",dist_en:"Hang Dong"},
{dist_code:"5018",dist_th:"อมก๋อย",dist_en:"Omkoi"},
{dist_code:"5016",dist_th:"ฮอด",dist_en:"Hot"},
{dist_code:"9202",dist_th:"กันตัง",dist_en:"Kantang"},
{dist_code:"9208",dist_th:"นาโยง",dist_en:"Na Yong"},
{dist_code:"9204",dist_th:"ปะเหลียน",dist_en:"Palian"},
{dist_code:"9201",dist_th:"เมืองตรัง",dist_en:"Mueang Trang"},
{dist_code:"9203",dist_th:"ย่านตาขาว",dist_en:"Yan Ta Khao"},
{dist_code:"9209",dist_th:"รัษฎา",dist_en:"Ratsada"},
{dist_code:"9207",dist_th:"วังวิเศษ",dist_en:"Wang Wiset"},
{dist_code:"9205",dist_th:"สิเกา",dist_en:"Sikao"},
{dist_code:"9206",dist_th:"ห้วยยอด",dist_en:"Huai Yot"},
{dist_code:"9210",dist_th:"หาดสำราญ",dist_en:"Hat Samran"},
{dist_code:"2306",dist_th:"เกาะกูด",dist_en:"Ko Kut"},
{dist_code:"2307",dist_th:"เกาะช้าง",dist_en:"Ko Chang"},
{dist_code:"2303",dist_th:"เขาสมิง",dist_en:"Khao Saming"},
{dist_code:"2302",dist_th:"คลองใหญ่",dist_en:"Khlong Yai"},
{dist_code:"2304",dist_th:"บ่อไร่",dist_en:"Bo Rai"},
{dist_code:"2301",dist_th:"เมืองตราด",dist_en:"Mueang Trat"},
{dist_code:"2305",dist_th:"แหลมงอบ",dist_en:"Laem Ngop"},
{dist_code:"6305",dist_th:"ท่าสองยาง",dist_en:"Tha Song Yang"},
{dist_code:"6302",dist_th:"บ้านตาก",dist_en:"Ban Tak"},
{dist_code:"6307",dist_th:"พบพระ",dist_en:"Phop Phra"},
{dist_code:"6301",dist_th:"เมืองตาก",dist_en:"Mueang Tak"},
{dist_code:"6304",dist_th:"แม่ระมาด",dist_en:"Mae Ramat"},
{dist_code:"6306",dist_th:"แม่สอด",dist_en:"Mae Sot"},
{dist_code:"6309",dist_th:"วังเจ้า",dist_en:"Wang Chao"},
{dist_code:"6303",dist_th:"สามเงา",dist_en:"Sam Ngao"},
{dist_code:"6308",dist_th:"อุ้มผาง",dist_en:"Umphang"},
{dist_code:"2603",dist_th:"บ้านนา",dist_en:"Ban Na"},
{dist_code:"2602",dist_th:"ปากพลี",dist_en:"Pak Phli"},
{dist_code:"2601",dist_th:"เมืองนครนายก",dist_en:"Mueang Nakhon Nayok"},
{dist_code:"2604",dist_th:"องครักษ์",dist_en:"Ongkharak"},
{dist_code:"7302",dist_th:"กำแพงแสน",dist_en:"Kamphaeng Saen"},
{dist_code:"7304",dist_th:"ดอนตูม",dist_en:"Don Tum"},
{dist_code:"7303",dist_th:"นครชัยศรี",dist_en:"Nakhon Chai Si"},
{dist_code:"7305",dist_th:"บางเลน",dist_en:"Bang Len"},
{dist_code:"7307",dist_th:"พุทธมณฑล",dist_en:"Phutthamonthon"},
{dist_code:"7301",dist_th:"เมืองนครปฐม",dist_en:"Mueang Nakhon Pathom"},
{dist_code:"7306",dist_th:"สามพราน",dist_en:"Sam Phran"},
{dist_code:"4803",dist_th:"ท่าอุเทน",dist_en:"Tha Uthen"},
{dist_code:"4805",dist_th:"ธาตุพนม",dist_en:"That Phanom"},
{dist_code:"4807",dist_th:"นาแก",dist_en:"Na Kae"},
{dist_code:"4811",dist_th:"นาทม",dist_en:"Na Thom"},
{dist_code:"4809",dist_th:"นาหว้า",dist_en:"Na Wa"},
{dist_code:"4804",dist_th:"บ้านแพง",dist_en:"Ban Phaeng"},
{dist_code:"4802",dist_th:"ปลาปาก",dist_en:"Pla Pak"},
{dist_code:"4810",dist_th:"โพนสวรรค์",dist_en:"Phon Sawan"},
{dist_code:"4801",dist_th:"เมืองนครพนม",dist_en:"Mueang Nakhon Phanom"},
{dist_code:"4806",dist_th:"เรณูนคร",dist_en:"Renu Nakhon"},
{dist_code:"4812",dist_th:"วังยาง",dist_en:"Wang Yang"},
{dist_code:"4808",dist_th:"ศรีสงคราม",dist_en:"Si Songkhram"},
{dist_code:"3023",dist_th:"แก้งสนามนาง",dist_en:"Kaeng Sanam Nang"},
{dist_code:"3019",dist_th:"ขามทะเลสอ",dist_en:"Kham Thale So"},
{dist_code:"3011",dist_th:"ขามสะแกแสง",dist_en:"Kham Sakaesaeng"},
{dist_code:"3004",dist_th:"คง",dist_en:"Khong"},
{dist_code:"3002",dist_th:"ครบุรี",dist_en:"Khon Buri"},
{dist_code:"3006",dist_th:"จักราช",dist_en:"Chakkarat"},
{dist_code:"3032",dist_th:"เฉลิมพระเกียรติ",dist_en:"Chaloem Phra Kiat"},
{dist_code:"3017",dist_th:"ชุมพวง",dist_en:"Chum Phuang"},
{dist_code:"3007",dist_th:"โชคชัย",dist_en:"Chok Chai"},
{dist_code:"3008",dist_th:"ด่านขุนทด",dist_en:"Dan Khun Thot"},
{dist_code:"3026",dist_th:"เทพารักษ์",dist_en:"Thepharak"},
{dist_code:"3024",dist_th:"โนนแดง",dist_en:"Non Daeng"},
{dist_code:"3009",dist_th:"โนนไทย",dist_en:"Non Thai"},
{dist_code:"3010",dist_th:"โนนสูง",dist_en:"Non Sung"},
{dist_code:"3030",dist_th:"บัวลาย",dist_en:"Bua Lai"},
{dist_code:"3012",dist_th:"บัวใหญ่",dist_en:"Bua Yai"},
{dist_code:"3005",dist_th:"บ้านเหลื่อม",dist_en:"Ban Lueam"},
{dist_code:"3013",dist_th:"ประทาย",dist_en:"Prathai"},
{dist_code:"3014",dist_th:"ปักธงชัย",dist_en:"Pak Thong Chai"},
{dist_code:"3021",dist_th:"ปากช่อง",dist_en:"Pak Chong"},
{dist_code:"3028",dist_th:"พระทองคำ",dist_en:"Phra Thong Kham"},
{dist_code:"3015",dist_th:"พิมาย",dist_en:"Phimai"},
{dist_code:"3001",dist_th:"เมืองนครราชสีมา",dist_en:"Mueang Nakhon Ratchasima"},
{dist_code:"3027",dist_th:"เมืองยาง",dist_en:"Mueang Yang"},
{dist_code:"3029",dist_th:"ลำทะเมนชัย",dist_en:"Lam Thamenchai"},
{dist_code:"3025",dist_th:"วังน้ำเขียว",dist_en:"Wang Nam Khiao"},
{dist_code:"3020",dist_th:"สีคิ้ว",dist_en:"Sikhio"},
{dist_code:"3031",dist_th:"สีดา",dist_en:"Sida"},
{dist_code:"3018",dist_th:"สูงเนิน",dist_en:"Sung Noen"},
{dist_code:"3003",dist_th:"เสิงสาง",dist_en:"Soeng Sang"},
{dist_code:"3022",dist_th:"หนองบุญมาก",dist_en:"Nong Bun Mak"},
{dist_code:"3016",dist_th:"ห้วยแถลง",dist_en:"Huai Thalaeng"},
{dist_code:"8015",dist_th:"ขนอม",dist_en:"Khanom"},
{dist_code:"8019",dist_th:"จุฬาภรณ์",dist_en:"Chulabhorn"},
{dist_code:"8004",dist_th:"ฉวาง",dist_en:"Chawang"},
{dist_code:"8023",dist_th:"เฉลิมพระเกียรติ",dist_en:"Chaloem Phra Kiat"},
{dist_code:"8007",dist_th:"ชะอวด",dist_en:"Cha-Uat"},
{dist_code:"8022",dist_th:"ช้างกลาง",dist_en:"Chang Klang"},
{dist_code:"8006",dist_th:"เชียรใหญ่",dist_en:"Chian Yai"},
{dist_code:"8018",dist_th:"ถ้ำพรรณรา",dist_en:"Tham Phannara"},
{dist_code:"8008",dist_th:"ท่าศาลา",dist_en:"Tha Sala"},
{dist_code:"8009",dist_th:"ทุ่งสง",dist_en:"Thung Song"},
{dist_code:"8011",dist_th:"ทุ่งใหญ่",dist_en:"Thung Yai"},
{dist_code:"8021",dist_th:"นบพิตำ",dist_en:"Nopphitam"},
{dist_code:"8010",dist_th:"นาบอน",dist_en:"Na Bon"},
{dist_code:"8017",dist_th:"บางขัน",dist_en:"Bang Khan"},
{dist_code:"8012",dist_th:"ปากพนัง",dist_en:"Pak Phanang"},
{dist_code:"8002",dist_th:"พรหมคีรี",dist_en:"Phrom Khiri"},
{dist_code:"8020",dist_th:"พระพรหม",dist_en:"Phra Phrom"},
{dist_code:"8005",dist_th:"พิปูน",dist_en:"Phipun"},
{dist_code:"8001",dist_th:"เมืองนครศรีธรรมราช",dist_en:"Mueang Nakhon Si Thammarat"},
{dist_code:"8013",dist_th:"ร่อนพิบูลย์",dist_en:"Ron Phibun"},
{dist_code:"8003",dist_th:"ลานสกา",dist_en:"Lan Saka"},
{dist_code:"8014",dist_th:"สิชล",dist_en:"Sichon"},
{dist_code:"8016",dist_th:"หัวไทร",dist_en:"Hua Sai"},
{dist_code:"6006",dist_th:"เก้าเลี้ยว",dist_en:"Kao Liao"},
{dist_code:"6002",dist_th:"โกรกพระ",dist_en:"Krok Phra"},
{dist_code:"6015",dist_th:"ชุมตาบง",dist_en:"Chum Ta Bong"},
{dist_code:"6003",dist_th:"ชุมแสง",dist_en:"Chum Saeng"},
{dist_code:"6012",dist_th:"ตากฟ้า",dist_en:"Tak Fa"},
{dist_code:"6007",dist_th:"ตาคลี",dist_en:"Takhli"},
{dist_code:"6008",dist_th:"ท่าตะโก",dist_en:"Tha Tako"},
{dist_code:"6005",dist_th:"บรรพตพิสัย",dist_en:"Banphot Phisai"},
{dist_code:"6010",dist_th:"พยุหะคีรี",dist_en:"Phayuha Khiri"},
{dist_code:"6009",dist_th:"ไพศาลี",dist_en:"Phaisali"},
{dist_code:"6001",dist_th:"เมืองนครสวรรค์",dist_en:"Mueang Nakhon Sawan"},
{dist_code:"6014",dist_th:"แม่เปิน",dist_en:"Mae Poen"},
{dist_code:"6013",dist_th:"แม่วงก์",dist_en:"Mae Wong"},
{dist_code:"6011",dist_th:"ลาดยาว",dist_en:"Lat Yao"},
{dist_code:"6004",dist_th:"หนองบัว",dist_en:"Nong Bua"},
{dist_code:"1205",dist_th:"ไทรน้อย",dist_en:"Sai Noi"},
{dist_code:"1202",dist_th:"บางกรวย",dist_en:"Bang Kruai"},
{dist_code:"1204",dist_th:"บางบัวทอง",dist_en:"Bang Bua Thong"},
{dist_code:"1203",dist_th:"บางใหญ่",dist_en:"Bang Yai"},
{dist_code:"1206",dist_th:"ปากเกร็ด",dist_en:"Pak Kret"},
{dist_code:"1201",dist_th:"เมืองนนทบุรี",dist_en:"Mueang Nonthaburi"},
{dist_code:"9612",dist_th:"จะแนะ",dist_en:"Chanae"},
{dist_code:"9613",dist_th:"เจาะไอร้อง",dist_en:"Cho-Airong"},
{dist_code:"9602",dist_th:"ตากใบ",dist_en:"Tak Bai"},
{dist_code:"9603",dist_th:"บาเจาะ",dist_en:"Bacho"},
{dist_code:"9601",dist_th:"เมืองนราธิวาส",dist_en:"Mueang Narathiwat"},
{dist_code:"9604",dist_th:"ยี่งอ",dist_en:"Yi-Ngo"},
{dist_code:"9605",dist_th:"ระแงะ",dist_en:"Ra-Ngae"},
{dist_code:"9606",dist_th:"รือเสาะ",dist_en:"Rueso"},
{dist_code:"9608",dist_th:"แว้ง",dist_en:"Waeng"},
{dist_code:"9607",dist_th:"ศรีสาคร",dist_en:"Si Sakhon"},
{dist_code:"9609",dist_th:"สุคิริน",dist_en:"Sukhirin"},
{dist_code:"9610",dist_th:"สุไหงโก-ลก",dist_en:"Su-Ngai Kolok"},
{dist_code:"9611",dist_th:"สุไหงปาดี",dist_en:"Su-Ngai Padi"},
{dist_code:"5515",dist_th:"เฉลิมพระเกียรติ",dist_en:"Chaloem Phra Kiat"},
{dist_code:"5509",dist_th:"เชียงกลาง",dist_en:"Chiang Klang"},
{dist_code:"5506",dist_th:"ท่าวังผา",dist_en:"Tha Wang Pha"},
{dist_code:"5508",dist_th:"ทุ่งช้าง",dist_en:"Thung Chang"},
{dist_code:"5504",dist_th:"นาน้อย",dist_en:"Na Noi"},
{dist_code:"5510",dist_th:"นาหมื่น",dist_en:"Na Muen"},
{dist_code:"5512",dist_th:"บ่อเกลือ",dist_en:"Bo Kluea"},
{dist_code:"5503",dist_th:"บ้านหลวง",dist_en:"Ban Luang"},
{dist_code:"5505",dist_th:"ปัว",dist_en:"Pua"},
{dist_code:"5514",dist_th:"ภูเพียง",dist_en:"Phu Phiang"},
{dist_code:"5501",dist_th:"เมืองน่าน",dist_en:"Mueang Nan"},
{dist_code:"5502",dist_th:"แม่จริม",dist_en:"Mae Charim"},
{dist_code:"5507",dist_th:"เวียงสา",dist_en:"Wiang Sa"},
{dist_code:"5513",dist_th:"สองแคว",dist_en:"Song Khwae"},
{dist_code:"5511",dist_th:"สันติสุข",dist_en:"Santi Suk"},
{dist_code:"3804",dist_th:"เซกา",dist_en:"Seka"},
{dist_code:"3803",dist_th:"โซ่พิสัย",dist_en:"So Phisai"},
{dist_code:"3806",dist_th:"บึงโขงหลง",dist_en:"Bueng Khong Long"},
{dist_code:"3808",dist_th:"บุ่งคล้า",dist_en:"Bung Khla"},
{dist_code:"3805",dist_th:"ปากคาด",dist_en:"Pak Khat"},
{dist_code:"3802",dist_th:"พรเจริญ",dist_en:"Phon Charoen"},
{dist_code:"3801",dist_th:"เมืองบึงกาฬ",dist_en:"Mueang Bueng Kan"},
{dist_code:"3807",dist_th:"ศรีวิไล",dist_en:"Si Wilai"},
{dist_code:"3103",dist_th:"กระสัง",dist_en:"Krasang"},
{dist_code:"3102",dist_th:"คูเมือง",dist_en:"Khu Mueang"},
{dist_code:"3122",dist_th:"แคนดง",dist_en:"Khaen Dong"},
{dist_code:"3123",dist_th:"เฉลิมพระเกียรติ",dist_en:"Chaloem Phra Kiat"},
{dist_code:"3118",dist_th:"ชำนิ",dist_en:"Chamni"},
{dist_code:"3104",dist_th:"นางรอง",dist_en:"Nang Rong"},
{dist_code:"3113",dist_th:"นาโพธิ์",dist_en:"Na Pho"},
{dist_code:"3120",dist_th:"โนนดินแดง",dist_en:"Non Din Daeng"},
{dist_code:"3117",dist_th:"โนนสุวรรณ",dist_en:"Non Suwan"},
{dist_code:"3108",dist_th:"บ้านกรวด",dist_en:"Ban Kruat"},
{dist_code:"3121",dist_th:"บ้านด่าน",dist_en:"Ban Dan"},
{dist_code:"3119",dist_th:"บ้านใหม่ไชยพจน์",dist_en:"Ban Mai Chaiyaphot"},
{dist_code:"3107",dist_th:"ประโคนชัย",dist_en:"Prakhon Chai"},
{dist_code:"3112",dist_th:"ปะคำ",dist_en:"Pakham"},
{dist_code:"3115",dist_th:"พลับพลาชัย",dist_en:"Phlapphla Chai"},
{dist_code:"3109",dist_th:"พุทไธสง",dist_en:"Phutthaisong"},
{dist_code:"3101",dist_th:"เมืองบุรีรัมย์",dist_en:"Mueang Buri Ram"},
{dist_code:"3106",dist_th:"ละหานทราย",dist_en:"Lahan Sai"},
{dist_code:"3110",dist_th:"ลำปลายมาศ",dist_en:"Lam Plai Mat"},
{dist_code:"3111",dist_th:"สตึก",dist_en:"Satuek"},
{dist_code:"3105",dist_th:"หนองกี่",dist_en:"Nong Ki"},
{dist_code:"3114",dist_th:"หนองหงส์",dist_en:"Nong Hong"},
{dist_code:"3116",dist_th:"ห้วยราช",dist_en:"Huai Rat"},
{dist_code:"1302",dist_th:"คลองหลวง",dist_en:"Khlong Luang"},
{dist_code:"1303",dist_th:"ธัญบุรี",dist_en:"Thanyaburi"},
{dist_code:"1301",dist_th:"เมืองปทุมธานี",dist_en:"Mueang Pathum Thani"},
{dist_code:"1305",dist_th:"ลาดหลุมแก้ว",dist_en:"Lat Lum Kaeo"},
{dist_code:"1306",dist_th:"ลำลูกกา",dist_en:"Lam Luk Ka"},
{dist_code:"1307",dist_th:"สามโคก",dist_en:"Sam Khok"},
{dist_code:"1304",dist_th:"หนองเสือ",dist_en:"Nong Suea"},
{dist_code:"7702",dist_th:"กุยบุรี",dist_en:"Kui Buri"},
{dist_code:"7703",dist_th:"ทับสะแก",dist_en:"Thap Sakae"},
{dist_code:"7704",dist_th:"บางสะพาน",dist_en:"Bang Saphan"},
{dist_code:"7705",dist_th:"บางสะพานน้อย",dist_en:"Bang Saphan Noi"},
{dist_code:"7706",dist_th:"ปราณบุรี",dist_en:"Pran Buri"},
{dist_code:"7701",dist_th:"เมืองประจวบคีรีขันธ์",dist_en:"Mueang Prachuap Khiri Khan"},
{dist_code:"7708",dist_th:"สามร้อยยอด",dist_en:"Sam Roi Yot"},
{dist_code:"7707",dist_th:"หัวหิน",dist_en:"Hua Hin"},
{dist_code:"2502",dist_th:"กบินทร์บุรี",dist_en:"Kabin Buri"},
{dist_code:"2503",dist_th:"นาดี",dist_en:"Na Di"},
{dist_code:"2506",dist_th:"บ้านสร้าง",dist_en:"Ban Sang"},
{dist_code:"2507",dist_th:"ประจันตคาม",dist_en:"Prachantakham"},
{dist_code:"2501",dist_th:"เมืองปราจีนบุรี",dist_en:"Mueang Prachin Buri"},
{dist_code:"2508",dist_th:"ศรีมหาโพธิ",dist_en:"Si Maha Phot"},
{dist_code:"2509",dist_th:"ศรีมโหสถ",dist_en:"Si Mahosot"},
{dist_code:"9411",dist_th:"กะพ้อ",dist_en:"Kapho"},
{dist_code:"9402",dist_th:"โคกโพธิ์",dist_en:"Khok Pho"},
{dist_code:"9406",dist_th:"ทุ่งยางแดง",dist_en:"Thung Yang Daeng"},
{dist_code:"9404",dist_th:"ปะนาเระ",dist_en:"Panare"},
{dist_code:"9405",dist_th:"มายอ",dist_en:"Mayo"},
{dist_code:"9401",dist_th:"เมืองปัตตานี",dist_en:"Mueang Pattani"},
{dist_code:"9412",dist_th:"แม่ลาน",dist_en:"Mae Lan"},
{dist_code:"9408",dist_th:"ไม้แก่น",dist_en:"Mai Kaen"},
{dist_code:"9410",dist_th:"ยะรัง",dist_en:"Yarang"},
{dist_code:"9409",dist_th:"ยะหริ่ง",dist_en:"Yaring"},
{dist_code:"9407",dist_th:"สายบุรี",dist_en:"Sai Buri"},
{dist_code:"9403",dist_th:"หนองจิก",dist_en:"Nong Chik"},
{dist_code:"1402",dist_th:"ท่าเรือ",dist_en:"Tha Ruea"},
{dist_code:"1403",dist_th:"นครหลวง",dist_en:"Nakhon Luang"},
{dist_code:"1413",dist_th:"บางซ้าย",dist_en:"Bang Sai"},
{dist_code:"1404",dist_th:"บางไทร",dist_en:"Bang Sai"},
{dist_code:"1405",dist_th:"บางบาล",dist_en:"Bang Ban"},
{dist_code:"1407",dist_th:"บางปะหัน",dist_en:"Bang Pahan"},
{dist_code:"1406",dist_th:"บางปะอิน",dist_en:"Bang Pa-In"},
{dist_code:"1416",dist_th:"บ้านแพรก",dist_en:"Ban Phraek"},
{dist_code:"1408",dist_th:"ผักไห่",dist_en:"Phak Hai"},
{dist_code:"1401",dist_th:"พระนครศรีอยุธยา",dist_en:"Phra Nakhon Si Ayutthaya"},
{dist_code:"1409",dist_th:"ภาชี",dist_en:"Phachi"},
{dist_code:"1415",dist_th:"มหาราช",dist_en:"Maha Rat"},
{dist_code:"1410",dist_th:"ลาดบัวหลวง",dist_en:"Lat Bua Luang"},
{dist_code:"1411",dist_th:"วังน้อย",dist_en:"Wang Noi"},
{dist_code:"1412",dist_th:"เสนา",dist_en:"Sena"},
{dist_code:"1414",dist_th:"อุทัย",dist_en:"Uthai"},
{dist_code:"5602",dist_th:"จุน",dist_en:"Chun"},
{dist_code:"5603",dist_th:"เชียงคำ",dist_en:"Chiang Kham"},
{dist_code:"5604",dist_th:"เชียงม่วน",dist_en:"Chiang Muan"},
{dist_code:"5605",dist_th:"ดอกคำใต้",dist_en:"Dok Khamtai"},
{dist_code:"5606",dist_th:"ปง",dist_en:"Pong"},
{dist_code:"5609",dist_th:"ภูกามยาว",dist_en:"Phu Kamyao"},
{dist_code:"5608",dist_th:"ภูซาง",dist_en:"Phu Sang"},
{dist_code:"5601",dist_th:"เมืองพะเยา",dist_en:"Mueang Phayao"},
{dist_code:"5607",dist_th:"แม่ใจ",dist_en:"Mae Chai"},
{dist_code:"8203",dist_th:"กะปง",dist_en:"Kapong"},
{dist_code:"8202",dist_th:"เกาะยาว",dist_en:"Ko Yao"},
{dist_code:"8206",dist_th:"คุระบุรี",dist_en:"Khura Buri"},
{dist_code:"8204",dist_th:"ตะกั่วทุ่ง",dist_en:"Takua Thung"},
{dist_code:"8205",dist_th:"ตะกั่วป่า",dist_en:"Takua Pa"},
{dist_code:"8207",dist_th:"ทับปุด",dist_en:"Thap Put"},
{dist_code:"8208",dist_th:"ท้ายเหมือง",dist_en:"Thai Mueang"},
{dist_code:"8201",dist_th:"เมืองพังงา",dist_en:"Mueang Phangnga"},
{dist_code:"9302",dist_th:"กงหรา",dist_en:"Kong Ra"},
{dist_code:"9303",dist_th:"เขาชัยสน",dist_en:"Khao Chaison"},
{dist_code:"9305",dist_th:"ควนขนุน",dist_en:"Khuan Khanun"},
{dist_code:"9304",dist_th:"ตะโหมด",dist_en:"Tamot"},
{dist_code:"9309",dist_th:"บางแก้ว",dist_en:"Bang Kaeo"},
{dist_code:"9306",dist_th:"ปากพะยูน",dist_en:"Pak Phayun"},
{dist_code:"9308",dist_th:"ป่าบอน",dist_en:"Pa Bon"},
{dist_code:"9310",dist_th:"ป่าพะยอม",dist_en:"Pa Phayom"},
{dist_code:"9301",dist_th:"เมืองพัทลุง",dist_en:"Mueang Phatthalung"},
{dist_code:"9311",dist_th:"ศรีนครินทร์",dist_en:"Srinagarindra"},
{dist_code:"9307",dist_th:"ศรีบรรพต",dist_en:"Si Banphot"},
{dist_code:"6611",dist_th:"ดงเจริญ",dist_en:"Dong Charoen"},
{dist_code:"6604",dist_th:"ตะพานหิน",dist_en:"Taphan Hin"},
{dist_code:"6608",dist_th:"ทับคล้อ",dist_en:"Tap Khlo"},
{dist_code:"6605",dist_th:"บางมูลนาก",dist_en:"Bang Mun Nak"},
{dist_code:"6610",dist_th:"บึงนาราง",dist_en:"Bueng Na Rang"},
{dist_code:"6606",dist_th:"โพทะเล",dist_en:"Pho Thale"},
{dist_code:"6603",dist_th:"โพธิ์ประทับช้าง",dist_en:"Pho Prathap Chang"},
{dist_code:"6601",dist_th:"เมืองพิจิตร",dist_en:"Mueang Phichit"},
{dist_code:"6612",dist_th:"วชิรบารมี",dist_en:"Wachirabarami"},
{dist_code:"6602",dist_th:"วังทรายพูน",dist_en:"Wang Sai Phun"},
{dist_code:"6609",dist_th:"สากเหล็ก",dist_en:"Sak Lek"},
{dist_code:"6607",dist_th:"สามง่าม",dist_en:"Sam Ngam"},
{dist_code:"6503",dist_th:"ชาติตระการ",dist_en:"Chat Trakan"},
{dist_code:"6502",dist_th:"นครไทย",dist_en:"Nakhon Thai"},
{dist_code:"6509",dist_th:"เนินมะปราง",dist_en:"Noen Maprang"},
{dist_code:"6505",dist_th:"บางกระทุ่ม",dist_en:"Bang Krathum"},
{dist_code:"6504",dist_th:"บางระกำ",dist_en:"Bang Rakam"},
{dist_code:"6506",dist_th:"พรหมพิราม",dist_en:"Phrom Phiram"},
{dist_code:"6501",dist_th:"เมืองพิษณุโลก",dist_en:"Mueang Phitsanulok"},
{dist_code:"6508",dist_th:"วังทอง",dist_en:"Wang Thong"},
{dist_code:"6507",dist_th:"วัดโบสถ์",dist_en:"Wat Bot"},
{dist_code:"7608",dist_th:"แก่งกระจาน",dist_en:"Kaeng Krachan"},
{dist_code:"7602",dist_th:"เขาย้อย",dist_en:"Khao Yoi"},
{dist_code:"7604",dist_th:"ชะอำ",dist_en:"Cha-Am"},
{dist_code:"7605",dist_th:"ท่ายาง",dist_en:"Tha Yang"},
{dist_code:"7606",dist_th:"บ้านลาด",dist_en:"Ban Lat"},
{dist_code:"7607",dist_th:"บ้านแหลม",dist_en:"Ban Laem"},
{dist_code:"7601",dist_th:"เมืองเพชรบุรี",dist_en:"Mueang Phetchaburi"},
{dist_code:"7603",dist_th:"หนองหญ้าปล้อง",dist_en:"Nong Ya Plong"},
{dist_code:"6711",dist_th:"เขาค้อ",dist_en:"Khao Kho"},
{dist_code:"6702",dist_th:"ชนแดน",dist_en:"Chon Daen"},
{dist_code:"6709",dist_th:"น้ำหนาว",dist_en:"Nam Nao"},
{dist_code:"6708",dist_th:"บึงสามพัน",dist_en:"Bueng Sam Phan"},
{dist_code:"6701",dist_th:"เมืองเพชรบูรณ์",dist_en:"Mueang Phetchabun"},
{dist_code:"6710",dist_th:"วังโป่ง",dist_en:"Wang Pong"},
{dist_code:"6705",dist_th:"วิเชียรบุรี",dist_en:"Wichian Buri"},
{dist_code:"6706",dist_th:"ศรีเทพ",dist_en:"Si Thep"},
{dist_code:"6707",dist_th:"หนองไผ่",dist_en:"Nong Phai"},
{dist_code:"6704",dist_th:"หล่มเก่า",dist_en:"Lom Kao"},
{dist_code:"6703",dist_th:"หล่มสัก",dist_en:"Lom Sak"},
{dist_code:"5405",dist_th:"เด่นชัย",dist_en:"Den Chai"},
{dist_code:"5401",dist_th:"เมืองแพร่",dist_en:"Mueang Phrae"},
{dist_code:"5402",dist_th:"ร้องกวาง",dist_en:"Rong Kwang"},
{dist_code:"5403",dist_th:"ลอง",dist_en:"Long"},
{dist_code:"5407",dist_th:"วังชิ้น",dist_en:"Wang Chin"},
{dist_code:"5406",dist_th:"สอง",dist_en:"Song"},
{dist_code:"5404",dist_th:"สูงเม่น",dist_en:"Sung Men"},
{dist_code:"5408",dist_th:"หนองม่วงไข่",dist_en:"Nong Muang Khai"},
{dist_code:"8302",dist_th:"กะทู้",dist_en:"Kathu"},
{dist_code:"8303",dist_th:"ถลาง",dist_en:"Thalang"},
{dist_code:"8301",dist_th:"เมืองภูเก็ต",dist_en:"Mueang Phuket"},
{dist_code:"4404",dist_th:"กันทรวิชัย",dist_en:"Kantharawichai"},
{dist_code:"4412",dist_th:"กุดรัง",dist_en:"Kut Rang"},
{dist_code:"4402",dist_th:"แกดำ",dist_en:"Kae Dam"},
{dist_code:"4403",dist_th:"โกสุมพิสัย",dist_en:"Kosum Phisai"},
{dist_code:"4413",dist_th:"ชื่นชม",dist_en:"Chuen Chom"},
{dist_code:"4405",dist_th:"เชียงยืน",dist_en:"Chiang Yuen"},
{dist_code:"4407",dist_th:"นาเชือก",dist_en:"Na Chueak"},
{dist_code:"4410",dist_th:"นาดูน",dist_en:"Na Dun"},
{dist_code:"4406",dist_th:"บรบือ",dist_en:"Borabue"},
{dist_code:"4408",dist_th:"พยัคฆภูมิพิสัย",dist_en:"Phayakkhaphum Phisai"},
{dist_code:"4401",dist_th:"เมืองมหาสารคาม",dist_en:"Mueang Maha Sarakham"},
{dist_code:"4411",dist_th:"ยางสีสุราช",dist_en:"Yang Sisurat"},
{dist_code:"4409",dist_th:"วาปีปทุม",dist_en:"Wapi Pathum"},
{dist_code:"4905",dist_th:"คำชะอี",dist_en:"Khamcha-I"},
{dist_code:"4904",dist_th:"ดงหลวง",dist_en:"Dong Luang"},
{dist_code:"4903",dist_th:"ดอนตาล",dist_en:"Don Tan"},
{dist_code:"4902",dist_th:"นิคมคำสร้อย",dist_en:"Nikhom Kham Soi"},
{dist_code:"4901",dist_th:"เมืองมุกดาหาร",dist_en:"Mueang Mukdahan"},
{dist_code:"4907",dist_th:"หนองสูง",dist_en:"Nong Sung"},
{dist_code:"4906",dist_th:"หว้านใหญ่",dist_en:"Wan Yai"},
{dist_code:"5802",dist_th:"ขุนยวม",dist_en:"Khun Yuam"},
{dist_code:"5807",dist_th:"ปางมะผ้า",dist_en:"Pang Mapha"},
{dist_code:"5803",dist_th:"ปาย",dist_en:"Pai"},
{dist_code:"5801",dist_th:"เมืองแม่ฮ่องสอน",dist_en:"Mueang Mae Hong Son"},
{dist_code:"5805",dist_th:"แม่ลาน้อย",dist_en:"Mae La Noi"},
{dist_code:"5804",dist_th:"แม่สะเรียง",dist_en:"Mae Sariang"},
{dist_code:"5806",dist_th:"สบเมย",dist_en:"Sop Moei"},
{dist_code:"3503",dist_th:"กุดชุม",dist_en:"Kut Chum"},
{dist_code:"3507",dist_th:"ค้อวัง",dist_en:"Kho Wang"},
{dist_code:"3504",dist_th:"คำเขื่อนแก้ว",dist_en:"Kham Khuean Kaeo"},
{dist_code:"3502",dist_th:"ทรายมูล",dist_en:"Sai Mun"},
{dist_code:"3509",dist_th:"ไทยเจริญ",dist_en:"Thai Charoen"},
{dist_code:"3505",dist_th:"ป่าติ้ว",dist_en:"Pa Tio"},
{dist_code:"3506",dist_th:"มหาชนะชัย",dist_en:"Maha Chana Chai"},
{dist_code:"3501",dist_th:"เมืองยโสธร",dist_en:"Mueang Yasothon"},
{dist_code:"3508",dist_th:"เลิงนกทา",dist_en:"Loeng Nok Tha"},
{dist_code:"9508",dist_th:"กรงปินัง",dist_en:"Krong Pinang"},
{dist_code:"9507",dist_th:"กาบัง",dist_en:"Kabang"},
{dist_code:"9504",dist_th:"ธารโต",dist_en:"Than To"},
{dist_code:"9503",dist_th:"บันนังสตา",dist_en:"Bannang Sata"},
{dist_code:"9502",dist_th:"เบตง",dist_en:"Betong"},
{dist_code:"9501",dist_th:"เมืองยะลา",dist_en:"Mueang Yala"},
{dist_code:"9505",dist_th:"ยะหา",dist_en:"Yaha"},
{dist_code:"9506",dist_th:"รามัน",dist_en:"Raman"},
{dist_code:"4502",dist_th:"เกษตรวิสัย",dist_en:"Kaset Wisai"},
{dist_code:"4504",dist_th:"จตุรพักตรพิมาน",dist_en:"Chaturaphak Phiman"},
{dist_code:"4517",dist_th:"จังหาร",dist_en:"Changhan"},
{dist_code:"4518",dist_th:"เชียงขวัญ",dist_en:"Chiang Khwan"},
{dist_code:"4520",dist_th:"ทุ่งเขาหลวง",dist_en:"Thung Khao Luang"},
{dist_code:"4505",dist_th:"ธวัชบุรี",dist_en:"Thawat Buri"},
{dist_code:"4503",dist_th:"ปทุมรัตต์",dist_en:"Pathum Rat"},
{dist_code:"4506",dist_th:"พนมไพร",dist_en:"Phanom Phrai"},
{dist_code:"4508",dist_th:"โพธิ์ชัย",dist_en:"Pho Chai"},
{dist_code:"4513",dist_th:"โพนทราย",dist_en:"Phon Sai"},
{dist_code:"4507",dist_th:"โพนทอง",dist_en:"Phon Thong"},
{dist_code:"4515",dist_th:"เมยวดี",dist_en:"Moei Wadi"},
{dist_code:"4501",dist_th:"เมืองร้อยเอ็ด",dist_en:"Mueang Roi Et"},
{dist_code:"4512",dist_th:"เมืองสรวง",dist_en:"Mueang Suang"},
{dist_code:"4516",dist_th:"ศรีสมเด็จ",dist_en:"Si Somdet"},
{dist_code:"4511",dist_th:"สุวรรณภูมิ",dist_en:"Suwannaphum"},
{dist_code:"4510",dist_th:"เสลภูมิ",dist_en:"Selaphum"},
{dist_code:"4509",dist_th:"หนองพอก",dist_en:"Nong Phok"},
{dist_code:"4519",dist_th:"หนองฮี",dist_en:"Nong Hi"},
{dist_code:"4514",dist_th:"อาจสามารถ",dist_en:"At Samat"},
{dist_code:"8504",dist_th:"กระบุรี",dist_en:"Kra Buri"},
{dist_code:"8503",dist_th:"กะเปอร์",dist_en:"Kapoe"},
{dist_code:"8501",dist_th:"เมืองระนอง",dist_en:"Mueang Ranong"},
{dist_code:"8502",dist_th:"ละอุ่น",dist_en:"La-Un"},
{dist_code:"8505",dist_th:"สุขสำราญ",dist_en:"Suk Samran"},
{dist_code:"2103",dist_th:"แกลง",dist_en:"Klaeng"},
{dist_code:"2107",dist_th:"เขาชะเมา",dist_en:"Khao Chamao"},
{dist_code:"2108",dist_th:"นิคมพัฒนา",dist_en:"Nikhom Phatthana"},
{dist_code:"2105",dist_th:"บ้านค่าย",dist_en:"Ban Khai"},
{dist_code:"2102",dist_th:"บ้านฉาง",dist_en:"Ban Chang"},
{dist_code:"2106",dist_th:"ปลวกแดง",dist_en:"Pluak Daeng"},
{dist_code:"2101",dist_th:"เมืองระยอง",dist_en:"Mueang Rayong"},
{dist_code:"2104",dist_th:"วังจันทร์",dist_en:"Wang Chan"},
{dist_code:"7002",dist_th:"จอมบึง",dist_en:"Chom Bueng"},
{dist_code:"7004",dist_th:"ดำเนินสะดวก",dist_en:"Damnoen Saduak"},
{dist_code:"7006",dist_th:"บางแพ",dist_en:"Bang Phae"},
{dist_code:"7010",dist_th:"บ้านคา",dist_en:"Ban Kha"},
{dist_code:"7005",dist_th:"บ้านโป่ง",dist_en:"Ban Pong"},
{dist_code:"7008",dist_th:"ปากท่อ",dist_en:"Pak Tho"},
{dist_code:"7007",dist_th:"โพธาราม",dist_en:"Photharam"},
{dist_code:"7001",dist_th:"เมืองราชบุรี",dist_en:"Mueang Ratchaburi"},
{dist_code:"7009",dist_th:"วัดเพลง",dist_en:"Wat Phleng"},
{dist_code:"7003",dist_th:"สวนผึ้ง",dist_en:"Suan Phueng"},
{dist_code:"1609",dist_th:"โคกเจริญ",dist_en:"Khok Charoen"},
{dist_code:"1603",dist_th:"โคกสำโรง",dist_en:"Khok Samrong"},
{dist_code:"1604",dist_th:"ชัยบาดาล",dist_en:"Chai Badan"},
{dist_code:"1605",dist_th:"ท่าวุ้ง",dist_en:"Tha Wung"},
{dist_code:"1607",dist_th:"ท่าหลวง",dist_en:"Tha Luang"},
{dist_code:"1606",dist_th:"บ้านหมี่",dist_en:"Ban Mi"},
{dist_code:"1602",dist_th:"พัฒนานิคม",dist_en:"Phatthana Nikhom"},
{dist_code:"1601",dist_th:"เมืองลพบุรี",dist_en:"Mueang Lop Buri"},
{dist_code:"1610",dist_th:"ลำสนธิ",dist_en:"Lam Sonthi"},
{dist_code:"1608",dist_th:"สระโบสถ์",dist_en:"Sa Bot"},
{dist_code:"1611",dist_th:"หนองม่วง",dist_en:"Nong Muang"},
{dist_code:"5203",dist_th:"เกาะคา",dist_en:"Ko Kha"},
{dist_code:"5205",dist_th:"งาว",dist_en:"Ngao"},
{dist_code:"5206",dist_th:"แจ้ห่ม",dist_en:"Chae Hom"},
{dist_code:"5208",dist_th:"เถิน",dist_en:"Thoen"},
{dist_code:"5213",dist_th:"เมืองปาน",dist_en:"Mueang Pan"},
{dist_code:"5201",dist_th:"เมืองลำปาง",dist_en:"Mueang Lampang"},
{dist_code:"5210",dist_th:"แม่ทะ",dist_en:"Mae Tha"},
{dist_code:"5209",dist_th:"แม่พริก",dist_en:"Mae Phrik"},
{dist_code:"5202",dist_th:"แม่เมาะ",dist_en:"Mae Mo"},
{dist_code:"5207",dist_th:"วังเหนือ",dist_en:"Wang Nuea"},
{dist_code:"5211",dist_th:"สบปราบ",dist_en:"Sop Prap"},
{dist_code:"5204",dist_th:"เสริมงาม",dist_en:"Soem Ngam"},
{dist_code:"5212",dist_th:"ห้างฉัตร",dist_en:"Hang Chat"},
{dist_code:"5105",dist_th:"ทุ่งหัวช้าง",dist_en:"Thung Hua Chang"},
{dist_code:"5107",dist_th:"บ้านธิ",dist_en:"Ban Thi"},
{dist_code:"5103",dist_th:"บ้านโฮ่ง",dist_en:"Ban Hong"},
{dist_code:"5106",dist_th:"ป่าซาง",dist_en:"Pa Sang"},
{dist_code:"5101",dist_th:"เมืองลำพูน",dist_en:"Mueang Lamphun"},
{dist_code:"5102",dist_th:"แม่ทา",dist_en:"Mae Tha"},
{dist_code:"5104",dist_th:"ลี้",dist_en:"Li"},
{dist_code:"5108",dist_th:"เวียงหนองล่อง",dist_en:"Wiang Nong Long"},
{dist_code:"4203",dist_th:"เชียงคาน",dist_en:"Chiang Khan"},
{dist_code:"4205",dist_th:"ด่านซ้าย",dist_en:"Dan Sai"},
{dist_code:"4208",dist_th:"ท่าลี่",dist_en:"Tha Li"},
{dist_code:"4202",dist_th:"นาด้วง",dist_en:"Na Duang"},
{dist_code:"4206",dist_th:"นาแห้ว",dist_en:"Na Haeo"},
{dist_code:"4204",dist_th:"ปากชม",dist_en:"Pak Chom"},
{dist_code:"4212",dist_th:"ผาขาว",dist_en:"Pha Khao"},
{dist_code:"4210",dist_th:"ภูกระดึง",dist_en:"Phu Kradueng"},
{dist_code:"4207",dist_th:"ภูเรือ",dist_en:"Phu Ruea"},
{dist_code:"4211",dist_th:"ภูหลวง",dist_en:"Phu Luang"},
{dist_code:"4201",dist_th:"เมืองเลย",dist_en:"Mueang Loei"},
{dist_code:"4209",dist_th:"วังสะพุง",dist_en:"Wang Saphung"},
{dist_code:"4214",dist_th:"หนองหิน",dist_en:"Nong Hin"},
{dist_code:"4213",dist_th:"เอราวัณ",dist_en:"Erawan"},
{dist_code:"3304",dist_th:"กันทรลักษ์",dist_en:"Kantharalak"},
{dist_code:"3303",dist_th:"กันทรารมย์",dist_en:"Kanthararom"},
{dist_code:"3305",dist_th:"ขุขันธ์",dist_en:"Khukhan"},
{dist_code:"3308",dist_th:"ขุนหาญ",dist_en:"Khun Han"},
{dist_code:"3315",dist_th:"น้ำเกลี้ยง",dist_en:"Nam Kliang"},
{dist_code:"3313",dist_th:"โนนคูณ",dist_en:"Non Khun"},
{dist_code:"3311",dist_th:"บึงบูรพ์",dist_en:"Bueng Bun"},
{dist_code:"3319",dist_th:"เบญจลักษ์",dist_en:"Benchalak"},
{dist_code:"3307",dist_th:"ปรางค์กู่",dist_en:"Prang Ku"},
{dist_code:"3320",dist_th:"พยุห์",dist_en:"Phayu"},
{dist_code:"3321",dist_th:"โพธิ์ศรีสุวรรณ",dist_en:"Pho Si Suwan"},
{dist_code:"3306",dist_th:"ไพรบึง",dist_en:"Phrai Bueng"},
{dist_code:"3317",dist_th:"ภูสิงห์",dist_en:"Phu Sing"},
{dist_code:"3318",dist_th:"เมืองจันทร์",dist_en:"Mueang Chan"},
{dist_code:"3301",dist_th:"เมืองศรีสะเกษ",dist_en:"Mueang Si Sa Ket"},
{dist_code:"3302",dist_th:"ยางชุมน้อย",dist_en:"Yang Chum Noi"},
{dist_code:"3309",dist_th:"ราษีไศล",dist_en:"Rasi Salai"},
{dist_code:"3316",dist_th:"วังหิน",dist_en:"Wang Hin"},
{dist_code:"3314",dist_th:"ศรีรัตนะ",dist_en:"Si Rattana"},
{dist_code:"3322",dist_th:"ศิลาลาด",dist_en:"Sila Lat"},
{dist_code:"3312",dist_th:"ห้วยทับทัน",dist_en:"Huai Thap Than"},
{dist_code:"3310",dist_th:"อุทุมพรพิสัย",dist_en:"Uthumphon Phisai"},
{dist_code:"4703",dist_th:"กุดบาก",dist_en:"Kut Bak"},
{dist_code:"4702",dist_th:"กุสุมาลย์",dist_en:"Kusuman"},
{dist_code:"4709",dist_th:"คำตากล้า",dist_en:"Kham Ta Kla"},
{dist_code:"4715",dist_th:"โคกศรีสุพรรณ",dist_en:"Khok Si Suphan"},
{dist_code:"4716",dist_th:"เจริญศิลป์",dist_en:"Charoen Sin"},
{dist_code:"4714",dist_th:"เต่างอย",dist_en:"Tao Ngoi"},
{dist_code:"4707",dist_th:"นิคมน้ำอูน",dist_en:"Nikhom Nam Un"},
{dist_code:"4710",dist_th:"บ้านม่วง",dist_en:"Ban Muang"},
{dist_code:"4704",dist_th:"พรรณานิคม",dist_en:"Phanna Nikhom"},
{dist_code:"4705",dist_th:"พังโคน",dist_en:"Phang Khon"},
{dist_code:"4717",dist_th:"โพนนาแก้ว",dist_en:"Phon Na Kaeo"},
{dist_code:"4718",dist_th:"ภูพาน",dist_en:"Phu Phan"},
{dist_code:"4701",dist_th:"เมืองสกลนคร",dist_en:"Mueang Sakon Nakhon"},
{dist_code:"4708",dist_th:"วานรนิวาส",dist_en:"Wanon Niwat"},
{dist_code:"4706",dist_th:"วาริชภูมิ",dist_en:"Waritchaphum"},
{dist_code:"4712",dist_th:"สว่างแดนดิน",dist_en:"Sawang Daen Din"},
{dist_code:"4713",dist_th:"ส่องดาว",dist_en:"Song Dao"},
{dist_code:"4711",dist_th:"อากาศอำนวย",dist_en:"Akat Amnuai"},
{dist_code:"9008",dist_th:"กระแสสินธุ์",dist_en:"Krasae Sin"},
{dist_code:"9016",dist_th:"คลองหอยโข่ง",dist_en:"Khlong Hoi Khong"},
{dist_code:"9013",dist_th:"ควนเนียง",dist_en:"Khuan Niang"},
{dist_code:"9003",dist_th:"จะนะ",dist_en:"Chana"},
{dist_code:"9005",dist_th:"เทพา",dist_en:"Thepha"},
{dist_code:"9004",dist_th:"นาทวี",dist_en:"Na Thawi"},
{dist_code:"9012",dist_th:"นาหม่อม",dist_en:"Na Mom"},
{dist_code:"9014",dist_th:"บางกล่ำ",dist_en:"Bang Klam"},
{dist_code:"9001",dist_th:"เมืองสงขลา",dist_en:"Mueang Songkhla"},
{dist_code:"9007",dist_th:"ระโนด",dist_en:"Ranot"},
{dist_code:"9009",dist_th:"รัตภูมิ",dist_en:"Rattaphum"},
{dist_code:"9002",dist_th:"สทิงพระ",dist_en:"Sathing Phra"},
{dist_code:"9010",dist_th:"สะเดา",dist_en:"Sadao"},
{dist_code:"9006",dist_th:"สะบ้าย้อย",dist_en:"Saba Yoi"},
{dist_code:"9015",dist_th:"สิงหนคร",dist_en:"Singhanakhon"},
{dist_code:"9011",dist_th:"หาดใหญ่",dist_en:"Hat Yai"},
{dist_code:"9103",dist_th:"ควนกาหลง",dist_en:"Khuan Kalong"},
{dist_code:"9102",dist_th:"ควนโดน",dist_en:"Khuan Don"},
{dist_code:"9104",dist_th:"ท่าแพ",dist_en:"Tha Phae"},
{dist_code:"9106",dist_th:"ทุ่งหว้า",dist_en:"Thung Wa"},
{dist_code:"9107",dist_th:"มะนัง",dist_en:"Manang"},
{dist_code:"9101",dist_th:"เมืองสตูล",dist_en:"Mueang Satun"},
{dist_code:"9105",dist_th:"ละงู",dist_en:"La-Ngu"},
{dist_code:"1102",dist_th:"บางบ่อ",dist_en:"Bang Bo"},
{dist_code:"1103",dist_th:"บางพลี",dist_en:"Bang Phli"},
{dist_code:"1106",dist_th:"บางเสาธง",dist_en:"Bang Sao Thong"},
{dist_code:"1104",dist_th:"พระประแดง",dist_en:"Phra Pradaeng"},
{dist_code:"1105",dist_th:"พระสมุทรเจดีย์",dist_en:"Phra Samut Chedi"},
{dist_code:"1101",dist_th:"เมืองสมุทรปราการ",dist_en:"Mueang Samut Prakan"},
{dist_code:"7502",dist_th:"บางคนที",dist_en:"Bang Khonthi"},
{dist_code:"7501",dist_th:"เมืองสมุทรสงคราม",dist_en:"Mueang Samut Songkhram"},
{dist_code:"7503",dist_th:"อัมพวา",dist_en:"Amphawa"},
{dist_code:"7402",dist_th:"กระทุ่มแบน",dist_en:"Krathum Baen"},
{dist_code:"7403",dist_th:"บ้านแพ้ว",dist_en:"Ban Phaeo"},
{dist_code:"7401",dist_th:"เมืองสมุทรสาคร",dist_en:"Mueang Samut Sakhon"},
{dist_code:"2707",dist_th:"เขาฉกรรจ์",dist_en:"Khao Chakan"},
{dist_code:"2702",dist_th:"คลองหาด",dist_en:"Khlong Hat"},
{dist_code:"2708",dist_th:"โคกสูง",dist_en:"Khok Sung"},
{dist_code:"2703",dist_th:"ตาพระยา",dist_en:"Ta Phraya"},
{dist_code:"2701",dist_th:"เมืองสระแก้ว",dist_en:"Mueang Sa Kaeo"},
{dist_code:"2704",dist_th:"วังน้ำเย็น",dist_en:"Wang Nam Yen"},
{dist_code:"2709",dist_th:"วังสมบูรณ์",dist_en:"Wang Sombun"},
{dist_code:"2705",dist_th:"วัฒนานคร",dist_en:"Watthana Nakhon"},
{dist_code:"2706",dist_th:"อรัญประเทศ",dist_en:"Aranyaprathet"},
{dist_code:"1902",dist_th:"แก่งคอย",dist_en:"Kaeng Khoi"},
{dist_code:"1913",dist_th:"เฉลิมพระเกียรติ",dist_en:"Chaloem Phra Kiat"},
{dist_code:"1907",dist_th:"ดอนพุด",dist_en:"Don Phut"},
{dist_code:"1906",dist_th:"บ้านหมอ",dist_en:"Ban Mo"},
{dist_code:"1909",dist_th:"พระพุทธบาท",dist_en:"Phra Phutthabat"},
{dist_code:"1911",dist_th:"มวกเหล็ก",dist_en:"Muak Lek"},
{dist_code:"1901",dist_th:"เมืองสระบุรี",dist_en:"Mueang Saraburi"},
{dist_code:"1912",dist_th:"วังม่วง",dist_en:"Wang Muang"},
{dist_code:"1904",dist_th:"วิหารแดง",dist_en:"Wihan Daeng"},
{dist_code:"1910",dist_th:"เสาไห้",dist_en:"Sao Hai"},
{dist_code:"1903",dist_th:"หนองแค",dist_en:"Nong Khae"},
{dist_code:"1905",dist_th:"หนองแซง",dist_en:"Nong Saeng"},
{dist_code:"1908",dist_th:"หนองโดน",dist_en:"Nong Don"},
{dist_code:"1703",dist_th:"ค่ายบางระจัน",dist_en:"Khai Bang Rachan"},
{dist_code:"1705",dist_th:"ท่าช้าง",dist_en:"Tha Chang"},
{dist_code:"1702",dist_th:"บางระจัน",dist_en:"Bang Rachan"},
{dist_code:"1704",dist_th:"พรหมบุรี",dist_en:"Phrom Buri"},
{dist_code:"1701",dist_th:"เมืองสิงห์บุรี",dist_en:"Mueang Sing Buri"},
{dist_code:"1706",dist_th:"อินทร์บุรี",dist_en:"In Buri"},
{dist_code:"6404",dist_th:"กงไกรลาศ",dist_en:"Kong Krailat"},
{dist_code:"6403",dist_th:"คีรีมาศ",dist_en:"Khiri Mat"},
{dist_code:"6409",dist_th:"ทุ่งเสลี่ยม",dist_en:"Thung Saliam"},
{dist_code:"6402",dist_th:"บ้านด่านลานหอย",dist_en:"Ban Dan Lan Hoi"},
{dist_code:"6401",dist_th:"เมืองสุโขทัย",dist_en:"Mueang Sukhothai"},
{dist_code:"6408",dist_th:"ศรีนคร",dist_en:"Si Nakhon"},
{dist_code:"6405",dist_th:"ศรีสัชนาลัย",dist_en:"Si Satchanalai"},
{dist_code:"6406",dist_th:"ศรีสำโรง",dist_en:"Si Samrong"},
{dist_code:"6407",dist_th:"สวรรคโลก",dist_en:"Sawankhalok"},
{dist_code:"7206",dist_th:"ดอนเจดีย์",dist_en:"Don Chedi"},
{dist_code:"7203",dist_th:"ด่านช้าง",dist_en:"Dan Chang"},
{dist_code:"7202",dist_th:"เดิมบางนางบวช",dist_en:"Doem Bang Nang Buat"},
{dist_code:"7204",dist_th:"บางปลาม้า",dist_en:"Bang Pla Ma"},
{dist_code:"7201",dist_th:"เมืองสุพรรณบุรี",dist_en:"Mueang Suphan Buri"},
{dist_code:"7205",dist_th:"ศรีประจันต์",dist_en:"Si Prachan"},
{dist_code:"7207",dist_th:"สองพี่น้อง",dist_en:"Song Phi Nong"},
{dist_code:"7208",dist_th:"สามชุก",dist_en:"Sam Chuk"},
{dist_code:"7210",dist_th:"หนองหญ้าไซ",dist_en:"Nong Ya Sai"},
{dist_code:"7209",dist_th:"อู่ทอง",dist_en:"U Thong"},
{dist_code:"8402",dist_th:"กาญจนดิษฐ์",dist_en:"Kanchanadit"},
{dist_code:"8405",dist_th:"เกาะพะงัน",dist_en:"Ko Pha-Ngan"},
{dist_code:"8404",dist_th:"เกาะสมุย",dist_en:"Ko Samui"},
{dist_code:"8408",dist_th:"คีรีรัฐนิคม",dist_en:"Khiri Rat Nikhom"},
{dist_code:"8414",dist_th:"เคียนซา",dist_en:"Khian Sa"},
{dist_code:"8418",dist_th:"ชัยบุรี",dist_en:"Chai Buri"},
{dist_code:"8406",dist_th:"ไชยา",dist_en:"Chaiya"},
{dist_code:"8403",dist_th:"ดอนสัก",dist_en:"Don Sak"},
{dist_code:"8411",dist_th:"ท่าฉาง",dist_en:"Tha Chang"},
{dist_code:"8407",dist_th:"ท่าชนะ",dist_en:"Tha Chana"},
{dist_code:"8409",dist_th:"บ้านตาขุน",dist_en:"Ban Ta Khun"},
{dist_code:"8413",dist_th:"บ้านนาเดิม",dist_en:"Ban Na Doem"},
{dist_code:"8412",dist_th:"บ้านนาสาร",dist_en:"Ban Na San"},
{dist_code:"8410",dist_th:"พนม",dist_en:"Phanom"},
{dist_code:"8416",dist_th:"พระแสง",dist_en:"Phrasaeng"},
{dist_code:"8417",dist_th:"พุนพิน",dist_en:"Phunphin"},
{dist_code:"8401",dist_th:"เมืองสุราษฎร์ธานี",dist_en:"Mueang Surat Thani"},
{dist_code:"8419",dist_th:"วิภาวดี",dist_en:"Vibhavadi"},
{dist_code:"8415",dist_th:"เวียงสระ",dist_en:"Wiang Sa"},
{dist_code:"3206",dist_th:"กาบเชิง",dist_en:"Kap Choeng"},
{dist_code:"3216",dist_th:"เขวาสินรินทร์",dist_en:"Khwao Sin Rin"},
{dist_code:"3204",dist_th:"จอมพระ",dist_en:"Chom Phra"},
{dist_code:"3202",dist_th:"ชุมพลบุรี",dist_en:"Chumphon Buri"},
{dist_code:"3203",dist_th:"ท่าตูม",dist_en:"Tha Tum"},
{dist_code:"3217",dist_th:"โนนนารายณ์",dist_en:"Non Narai"},
{dist_code:"3213",dist_th:"บัวเชด",dist_en:"Buachet"},
{dist_code:"3205",dist_th:"ปราสาท",dist_en:"Prasat"},
{dist_code:"3214",dist_th:"พนมดงรัก",dist_en:"Phanom Dong Rak"},
{dist_code:"3201",dist_th:"เมืองสุรินทร์",dist_en:"Mueang Surin"},
{dist_code:"3207",dist_th:"รัตนบุรี",dist_en:"Rattanaburi"},
{dist_code:"3211",dist_th:"ลำดวน",dist_en:"Lamduan"},
{dist_code:"3215",dist_th:"ศรีณรงค์",dist_en:"Si Narong"},
{dist_code:"3209",dist_th:"ศีขรภูมิ",dist_en:"Sikhoraphum"},
{dist_code:"3208",dist_th:"สนม",dist_en:"Sanom"},
{dist_code:"3210",dist_th:"สังขะ",dist_en:"Sangkha"},
{dist_code:"3212",dist_th:"สำโรงทาบ",dist_en:"Samrong Thap"},
{dist_code:"4302",dist_th:"ท่าบ่อ",dist_en:"Tha Bo"},
{dist_code:"4315",dist_th:"เฝ้าไร่",dist_en:"Fao Rai"},
{dist_code:"4317",dist_th:"โพธิ์ตาก",dist_en:"Pho Tak"},
{dist_code:"4305",dist_th:"โพนพิสัย",dist_en:"Phon Phisai"},
{dist_code:"4301",dist_th:"เมืองหนองคาย",dist_en:"Mueang Nong Khai"},
{dist_code:"4316",dist_th:"รัตนวาปี",dist_en:"Rattanawapi"},
{dist_code:"4307",dist_th:"ศรีเชียงใหม่",dist_en:"Si Chiang Mai"},
{dist_code:"4314",dist_th:"สระใคร",dist_en:"Sakhrai"},
{dist_code:"4308",dist_th:"สังคม",dist_en:"Sangkhom"},
{dist_code:"3902",dist_th:"นากลาง",dist_en:"Na Klang"},
{dist_code:"3906",dist_th:"นาวัง",dist_en:"Na Wang"},
{dist_code:"3903",dist_th:"โนนสัง",dist_en:"Non Sang"},
{dist_code:"3901",dist_th:"เมืองหนองบัวลำภู",dist_en:"Mueang Nong Bua Lam Phu"},
{dist_code:"3904",dist_th:"ศรีบุญเรือง",dist_en:"Si Bun Rueang"},
{dist_code:"3905",dist_th:"สุวรรณคูหา",dist_en:"Suwannakhuha"},
{dist_code:"1502",dist_th:"ไชโย",dist_en:"Chaiyo"},
{dist_code:"1503",dist_th:"ป่าโมก",dist_en:"Pa Mok"},
{dist_code:"1504",dist_th:"โพธิ์ทอง",dist_en:"Pho Thong"},
{dist_code:"1501",dist_th:"เมืองอ่างทอง",dist_en:"Mueang Ang Thong"},
{dist_code:"1506",dist_th:"วิเศษชัยชาญ",dist_en:"Wiset Chai Chan"},
{dist_code:"1507",dist_th:"สามโก้",dist_en:"Samko"},
{dist_code:"1505",dist_th:"แสวงหา",dist_en:"Sawaeng Ha"},
{dist_code:"3702",dist_th:"ชานุมาน",dist_en:"Chanuman"},
{dist_code:"3703",dist_th:"ปทุมราชวงศา",dist_en:"Pathum Ratchawongsa"},
{dist_code:"3704",dist_th:"พนา",dist_en:"Phana"},
{dist_code:"3701",dist_th:"เมืองอำนาจเจริญ",dist_en:"Mueang Amnat Charoen"},
{dist_code:"3707",dist_th:"ลืออำนาจ",dist_en:"Lue Amnat"},
{dist_code:"3705",dist_th:"เสนางคนิคม",dist_en:"Senangkhanikhom"},
{dist_code:"3706",dist_th:"หัวตะพาน",dist_en:"Hua Taphan"},
{dist_code:"4102",dist_th:"กุดจับ",dist_en:"Kut Chap"},
{dist_code:"4104",dist_th:"กุมภวาปี",dist_en:"Kumphawapi"},
{dist_code:"4124",dist_th:"กู่แก้ว",dist_en:"Ku Kaeo"},
{dist_code:"4108",dist_th:"ไชยวาน",dist_en:"Chai Wan"},
{dist_code:"4107",dist_th:"ทุ่งฝน",dist_en:"Thung Fon"},
{dist_code:"4122",dist_th:"นายูง",dist_en:"Na Yung"},
{dist_code:"4118",dist_th:"น้ำโสม",dist_en:"Nam Som"},
{dist_code:"4105",dist_th:"โนนสะอาด",dist_en:"Non Sa-At"},
{dist_code:"4111",dist_th:"บ้านดุง",dist_en:"Ban Dung"},
{dist_code:"4117",dist_th:"บ้านผือ",dist_en:"Ban Phue"},
{dist_code:"4125",dist_th:"ประจักษ์ศิลปาคม",dist_en:"Prachaksinlapakhom"},
{dist_code:"4123",dist_th:"พิบูลย์รักษ์",dist_en:"Phibun Rak"},
{dist_code:"4119",dist_th:"เพ็ญ",dist_en:"Phen"},
{dist_code:"4101",dist_th:"เมืองอุดรธานี",dist_en:"Mueang Udon Thani"},
{dist_code:"4110",dist_th:"วังสามหมอ",dist_en:"Wang Sam Mo"},
{dist_code:"4109",dist_th:"ศรีธาตุ",dist_en:"Si That"},
{dist_code:"4120",dist_th:"สร้างคอม",dist_en:"Sang Khom"},
{dist_code:"4103",dist_th:"หนองวัวซอ",dist_en:"Nong Wua So"},
{dist_code:"4121",dist_th:"หนองแสง",dist_en:"Nong Saeng"},
{dist_code:"4106",dist_th:"หนองหาน",dist_en:"Nong Han"},
{dist_code:"5302",dist_th:"ตรอน",dist_en:"Tron"},
{dist_code:"5309",dist_th:"ทองแสนขัน",dist_en:"Thong Saen Khan"},
{dist_code:"5303",dist_th:"ท่าปลา",dist_en:"Tha Pla"},
{dist_code:"5304",dist_th:"น้ำปาด",dist_en:"Nam Pat"},
{dist_code:"5306",dist_th:"บ้านโคก",dist_en:"Ban Khok"},
{dist_code:"5307",dist_th:"พิชัย",dist_en:"Phichai"},
{dist_code:"5305",dist_th:"ฟากท่า",dist_en:"Fak Tha"},
{dist_code:"5301",dist_th:"เมืองอุตรดิตถ์",dist_en:"Mueang Uttaradit"},
{dist_code:"5308",dist_th:"ลับแล",dist_en:"Laplae"},
{dist_code:"6102",dist_th:"ทัพทัน",dist_en:"Thap Than"},
{dist_code:"6106",dist_th:"บ้านไร่",dist_en:"Ban Rai"},
{dist_code:"6101",dist_th:"เมืองอุทัยธานี",dist_en:"Mueang Uthai Thani"},
{dist_code:"6107",dist_th:"ลานสัก",dist_en:"Lan Sak"},
{dist_code:"6103",dist_th:"สว่างอารมณ์",dist_en:"Sawang Arom"},
{dist_code:"6105",dist_th:"หนองขาหย่าง",dist_en:"Nong Khayang"},
{dist_code:"6104",dist_th:"หนองฉาง",dist_en:"Nong Chang"},
{dist_code:"6108",dist_th:"ห้วยคต",dist_en:"Huai Khot"},
{dist_code:"3412",dist_th:"กุดข้าวปุ้น",dist_en:"Kut Khaopun"},
{dist_code:"3405",dist_th:"เขมราฐ",dist_en:"Khemarat"},
{dist_code:"3404",dist_th:"เขื่องใน",dist_en:"Khueang Nai"},
{dist_code:"3403",dist_th:"โขงเจียม",dist_en:"Khong Chiam"},
{dist_code:"3424",dist_th:"ดอนมดแดง",dist_en:"Don Mot Daeng"},
{dist_code:"3407",dist_th:"เดชอุดม",dist_en:"Det Udom"},
{dist_code:"3411",dist_th:"ตระการพืชผล",dist_en:"Trakan Phuet Phon"},
{dist_code:"3420",dist_th:"ตาลสุม",dist_en:"Tan Sum"},
{dist_code:"3426",dist_th:"ทุ่งศรีอุดม",dist_en:"Thung Si Udom"},
{dist_code:"3408",dist_th:"นาจะหลวย",dist_en:"Na Chaluai"},
{dist_code:"3430",dist_th:"นาตาล",dist_en:"Na Tan"},
{dist_code:"3429",dist_th:"นาเยีย",dist_en:"Na Yia"},
{dist_code:"3433",dist_th:"น้ำขุ่น",dist_en:"Nam Khun"},
{dist_code:"3409",dist_th:"น้ำยืน",dist_en:"Nam Yuen"},
{dist_code:"3410",dist_th:"บุณฑริก",dist_en:"Buntharik"},
{dist_code:"3419",dist_th:"พิบูลมังสาหาร",dist_en:"Phibun Mangsahan"},
{dist_code:"3421",dist_th:"โพธิ์ไทร",dist_en:"Pho Sai"},
{dist_code:"3414",dist_th:"ม่วงสามสิบ",dist_en:"Muang Sam Sip"},
{dist_code:"3401",dist_th:"เมืองอุบลราชธานี",dist_en:"Mueang Ubon Ratchathani"},
{dist_code:"3415",dist_th:"วารินชำราบ",dist_en:"Warin Chamrap"},
{dist_code:"3402",dist_th:"ศรีเมืองใหม่",dist_en:"Si Mueang Mai"},
{dist_code:"3432",dist_th:"สว่างวีระวงศ์",dist_en:"Sawang Wirawong"},
{dist_code:"3422",dist_th:"สำโรง",dist_en:"Samrong"},
{dist_code:"3425",dist_th:"สิรินธร",dist_en:"Sirindhorn"},
{dist_code:"3431",dist_th:"เหล่าเสือโก้ก",dist_en:"Lao Suea Kok"},
]