const prov = [
    {prov_code:"81",prov_th:"กระบี่",prov_en:"Krabi"},
{prov_code:"10",prov_th:"กรุงเทพมหานคร",prov_en:"Bangkok"},
{prov_code:"71",prov_th:"กาญจนบุรี",prov_en:"Kanchanaburi"},
{prov_code:"46",prov_th:"กาฬสินธุ์",prov_en:"Kalasin"},
{prov_code:"62",prov_th:"กำแพงเพชร",prov_en:"Kamphaeng Phet"},
{prov_code:"40",prov_th:"ขอนแก่น",prov_en:"Khon Kaen"},
{prov_code:"22",prov_th:"จันทบุรี",prov_en:"Chanthaburi"},
{prov_code:"24",prov_th:"ฉะเชิงเทรา",prov_en:"Chachoengsao"},
{prov_code:"20",prov_th:"ชลบุรี",prov_en:"Chon Buri"},
{prov_code:"18",prov_th:"ชัยนาท",prov_en:"Chai Nat"},
{prov_code:"36",prov_th:"ชัยภูมิ",prov_en:"Chaiyaphum"},
{prov_code:"86",prov_th:"ชุมพร",prov_en:"Chumphon"},
{prov_code:"57",prov_th:"เชียงราย",prov_en:"Chiang Rai"},
{prov_code:"50",prov_th:"เชียงใหม่",prov_en:"Chiang Mai"},
{prov_code:"92",prov_th:"ตรัง",prov_en:"Trang"},
{prov_code:"23",prov_th:"ตราด",prov_en:"Trat"},
{prov_code:"63",prov_th:"ตาก",prov_en:"Tak"},
{prov_code:"26",prov_th:"นครนายก",prov_en:"Nakhon Nayok"},
{prov_code:"73",prov_th:"นครปฐม",prov_en:"Nakhon Pathom"},
{prov_code:"48",prov_th:"นครพนม",prov_en:"Nakhon Phanom"},
{prov_code:"30",prov_th:"นครราชสีมา",prov_en:"Nakhon Ratchasima"},
{prov_code:"80",prov_th:"นครศรีธรรมราช",prov_en:"Nakhon Si Thammarat"},
{prov_code:"60",prov_th:"นครสวรรค์",prov_en:"Nakhon Sawan"},
{prov_code:"12",prov_th:"นนทบุรี",prov_en:"Nonthaburi"},
{prov_code:"96",prov_th:"นราธิวาส",prov_en:"Narathiwat"},
{prov_code:"55",prov_th:"น่าน",prov_en:"Nan"},
{prov_code:"38",prov_th:"บึงกาฬ",prov_en:"Bueng Kan"},
{prov_code:"31",prov_th:"บุรีรัมย์",prov_en:"Buri Ram"},
{prov_code:"13",prov_th:"ปทุมธานี",prov_en:"Pathum Thani"},
{prov_code:"77",prov_th:"ประจวบคีรีขันธ์",prov_en:"Prachuap Khiri Khan"},
{prov_code:"25",prov_th:"ปราจีนบุรี",prov_en:"Prachin Buri"},
{prov_code:"94",prov_th:"ปัตตานี",prov_en:"Pattani"},
{prov_code:"14",prov_th:"พระนครศรีอยุธยา",prov_en:"Phra Nakhon Si Ayutthaya"},
{prov_code:"56",prov_th:"พะเยา",prov_en:"Phayao"},
{prov_code:"82",prov_th:"พังงา",prov_en:"Phangnga"},
{prov_code:"93",prov_th:"พัทลุง",prov_en:"Phatthalung"},
{prov_code:"66",prov_th:"พิจิตร",prov_en:"Phichit"},
{prov_code:"65",prov_th:"พิษณุโลก",prov_en:"Phitsanulok"},
{prov_code:"76",prov_th:"เพชรบุรี",prov_en:"Phetchaburi"},
{prov_code:"67",prov_th:"เพชรบูรณ์",prov_en:"Phetchabun"},
{prov_code:"54",prov_th:"แพร่",prov_en:"Phrae"},
{prov_code:"83",prov_th:"ภูเก็ต",prov_en:"Phuket"},
{prov_code:"44",prov_th:"มหาสารคาม",prov_en:"Maha Sarakham"},
{prov_code:"49",prov_th:"มุกดาหาร",prov_en:"Mukdahan"},
{prov_code:"58",prov_th:"แม่ฮ่องสอน",prov_en:"Mae Hong Son"},
{prov_code:"35",prov_th:"ยโสธร",prov_en:"Yasothon"},
{prov_code:"95",prov_th:"ยะลา",prov_en:"Yala"},
{prov_code:"45",prov_th:"ร้อยเอ็ด",prov_en:"Roi Et"},
{prov_code:"85",prov_th:"ระนอง",prov_en:"Ranong"},
{prov_code:"21",prov_th:"ระยอง",prov_en:"Rayong"},
{prov_code:"70",prov_th:"ราชบุรี",prov_en:"Ratchaburi"},
{prov_code:"16",prov_th:"ลพบุรี",prov_en:"Lop Buri"},
{prov_code:"52",prov_th:"ลำปาง",prov_en:"Lampang"},
{prov_code:"51",prov_th:"ลำพูน",prov_en:"Lamphun"},
{prov_code:"42",prov_th:"เลย",prov_en:"Loei"},
{prov_code:"33",prov_th:"ศรีสะเกษ",prov_en:"Si Sa Ket"},
{prov_code:"47",prov_th:"สกลนคร",prov_en:"Sakon Nakhon"},
{prov_code:"90",prov_th:"สงขลา",prov_en:"Songkhla"},
{prov_code:"91",prov_th:"สตูล",prov_en:"Satun"},
{prov_code:"11",prov_th:"สมุทรปราการ",prov_en:"Samut Prakan"},
{prov_code:"75",prov_th:"สมุทรสงคราม",prov_en:"Samut Songkhram"},
{prov_code:"74",prov_th:"สมุทรสาคร",prov_en:"Samut Sakhon"},
{prov_code:"27",prov_th:"สระแก้ว",prov_en:"Sa Kaeo"},
{prov_code:"19",prov_th:"สระบุรี",prov_en:"Saraburi"},
{prov_code:"17",prov_th:"สิงห์บุรี",prov_en:"Sing Buri"},
{prov_code:"64",prov_th:"สุโขทัย",prov_en:"Sukhothai"},
{prov_code:"72",prov_th:"สุพรรณบุรี",prov_en:"Suphan Buri"},
{prov_code:"84",prov_th:"สุราษฎร์ธานี",prov_en:"Surat Thani"},
{prov_code:"32",prov_th:"สุรินทร์",prov_en:"Surin"},
{prov_code:"43",prov_th:"หนองคาย",prov_en:"Nong Khai"},
{prov_code:"39",prov_th:"หนองบัวลำภู",prov_en:"Nong Bua Lam Phu"},
{prov_code:"15",prov_th:"อ่างทอง",prov_en:"Ang Thong"},
{prov_code:"37",prov_th:"อำนาจเจริญ",prov_en:"Amnat Charoen"},
{prov_code:"41",prov_th:"อุดรธานี",prov_en:"Udon Thani"},
{prov_code:"53",prov_th:"อุตรดิตถ์",prov_en:"Uttaradit"},
{prov_code:"61",prov_th:"อุทัยธานี",prov_en:"Uthai Thani"},
{prov_code:"34",prov_th:"อุบลราชธานี",prov_en:"Ubon Ratchathani"},
]