let DONE = [
    `Thao Suranari Mosaic`,
    `สวนหลวง ร.9 : Gold Saint Set 02`,
    `สวนหลวง ร.9 : Gold Saint Set 01`,
    `ฉันเกิดในรัชกาลที่ ๙`,
    `I Was Born in the Reign of King Rama IX`,
    `Snowflake Thailand 2022`,
    `T.S.P.`,
    // ``,
    // ``,
    // ``,
    `Mueang Samut Prakan District`,
    `วัดพระปฐมเจดีย์`,
    `วัดพระปฐมเจดีย์ราชวรมหาวิหาร`,
    `Hua Lamphong Railway Station`,
    `Wat Phra Kaew`,
    `Memorial Bridge (Bangkok)`,
    `KASET BANNER`,
    `Saint seiya : 12 Castle Gold Sents`,
    `Around Samut Prakan Observation Tower`,
    `Exploring Chong Nonsi`,
    `Benchasiri Park`,
    `Samut Prakan Province`,
    `Toast of July - Benchasiri Park`,
    `Exploring Phaya Thai Palace`,
    `Chaozhou cemetery tour`,
    `Ingress Halloween 2021`,
    `Ingress Halloween 2020`,
    `Thonglor`,
    `Ekkamai`,
    `KU Mosaics`,
    `Ratchadamnoen mission 1`,
    `Siriraj Hospital`,
    `ChangChui`,
    `Rama VIII Bridge`,
    `Rama IX Bridge`,
    `Lumpini Park`,
    `ชม "เหี้ย" ในป่าเมือง`,
    `Yamato`,
    `seacon square srinakarin`,
    `Travel Suanluang RAMA IX Park`,
    `SONGKRAN BIG EVENT BANNER`,
    `Sun & Moon Central Rama 2`,
    `SS`,
    `Phutthamonthon Banner`,
    `The Way of Destroyer`,
    `Asoke is the best place in Bangkok`,
    `Temple in Rattanakosin Island`,
    `Welcome to Bangkok`,
    `TMB Island`,
    `Nonthaburi`,
    `วัดบางนาใน`,
    `Ratchadamnoen Avenue`,
    `MD: Bangkok Nostalgia`,
    `Explore Bangkok during Recursion Prime`,
    `Mini Siam`,
    `ขบวนเรือพยุหยาตราทางชลมารค`,
    `MD: Bangkok Song of the King`,
    `Holy Frog Series`,
    `พ่อขุนรามคำแหงมหาราช`,
    `Temple of the King RAMA I I (Wat Arun )`,
    `Temple of the King RAMA I (Wat Pho)`,
    `Silom Bangkok`,
    `KMUTT`,
    `Songkran Queen - MD Side Mission`,
    `ชมพูพันธุ์ทิพย์จตุจักร`,
    `Journey to heaven : เสด็จสู่สวรรคาลัย`,
    `MD: Songkran Festival`,
    `SEE - ALL - POTENTIAL - INSIDE`,
    `View from top of LPN Tower --night`,
    `The Great King Bhumibol Bridge`,
    `View from top of LPN Tower`,
    `SRT Cargo Train Banner`,
    `Rot Fai Park -SRT Passenger train`,
    `G Tower`,
    `Dusit Thani HOTEL`,
    `Siam Square Loop Walk`,
    `Snake farm`,
    `Frung`,
    `Sunset @ Suanluang Rama IX`,
]